// petstore-base API for pets
// Generated by @f3liz/rescript-autogen-openapi
// DO NOT EDIT - This file is auto-generated

S.enableJson()


type getpetsResponse = array<PetstoreBaseComponentSchemas.Pet.t>

let getpetsResponseSchema = S.array(PetstoreBaseComponentSchemas.Pet.schema)

/** List all pets */
let getpets = async (~fetch: (~url: string, ~method_: string, ~body: option<JSON.t>) => Promise.t<JSON.t>): getpetsResponse => {

  let response = await fetch(
    ~url="/pets",
    ~method_="GET",
    ~body=None,
  )
  response->S.parseOrThrow(getpetsResponseSchema)
}

type postpetsRequest = PetstoreBaseComponentSchemas.Pet.t

let postpetsRequestSchema = PetstoreBaseComponentSchemas.Pet.schema

type postpetsResponse = unit

/** Create a pet */
let postpets = async (~body: postpetsRequest, ~fetch: (~url: string, ~method_: string, ~body: option<JSON.t>) => Promise.t<JSON.t>): postpetsResponse => {
  let jsonBody = body->S.reverseConvertToJsonOrThrow(postpetsRequestSchema)
  let response = await fetch(
    ~url="/pets",
    ~method_="POST",
    ~body=Some(jsonBody),
  )
  let _ = response
}

type getpetsResponse = PetstoreBaseComponentSchemas.Pet.t

let getpetsResponseSchema = PetstoreBaseComponentSchemas.Pet.schema

/** Info for a specific pet */
let getpets = async (~fetch: (~url: string, ~method_: string, ~body: option<JSON.t>) => Promise.t<JSON.t>): getpetsResponse => {

  let response = await fetch(
    ~url="/pets/{petId}",
    ~method_="GET",
    ~body=None,
  )
  response->S.parseOrThrow(getpetsResponseSchema)
}
