// extended API for store
// Generated by @f3liz/rescript-autogen-openapi
// DO NOT EDIT - This file is auto-generated

S.enableJson()


type getstoreinventoryResponse = dict<JSON.t>

let getstoreinventoryResponseSchema = S.dict(S.json)

/** Returns pet inventories by status */
let getstoreinventory = async (~fetch: (~url: string, ~method_: string, ~body: option<JSON.t>) => Promise.t<JSON.t>): getstoreinventoryResponse => {

  let response = await fetch(
    ~url="/store/inventory",
    ~method_="GET",
    ~body=None,
  )
  response->S.parseOrThrow(getstoreinventoryResponseSchema)
}
