// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Pipeline from "../core/Pipeline.res.mjs";
import * as Toposort from "../bindings/Toposort.res.mjs";
import * as Templates from "../core/Templates.res.mjs";
import * as FileSystem from "../core/FileSystem.res.mjs";
import * as Handlebars from "../bindings/Handlebars.res.mjs";
import * as Stdlib_Dict from "@rescript/runtime/lib/es6/Stdlib_Dict.js";
import * as CodegenUtils from "../core/CodegenUtils.res.mjs";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as SchemaIRParser from "../core/SchemaIRParser.res.mjs";
import * as JsConvertCase from "js-convert-case";
import * as Primitive_string from "@rescript/runtime/lib/es6/Primitive_string.js";
import * as GenerationContext from "../types/GenerationContext.res.mjs";
import * as IRToSuryGenerator from "./IRToSuryGenerator.res.mjs";
import * as IRToTypeGenerator from "./IRToTypeGenerator.res.mjs";

function extractReferencedSchemaNames(_irType) {
  while (true) {
    let irType = _irType;
    if (typeof irType !== "object") {
      return [];
    }
    switch (irType.TAG) {
      case "Array" :
        _irType = irType.items;
        continue;
      case "Object" :
        return irType.properties.flatMap(param => extractReferencedSchemaNames(param[1]));
      case "Union" :
      case "Intersection" :
        return irType._0.flatMap(extractReferencedSchemaNames);
      case "Reference" :
        return [irType._0];
      case "Option" :
        _irType = irType._0;
        continue;
      default:
        return [];
    }
  };
}

function generate(spec, outputDir) {
  let match = Stdlib_Option.mapOr(Stdlib_Option.flatMap(spec.components, components => components.schemas), [
    {
      schemas: {}
    },
    []
  ], SchemaIRParser.parseComponentSchemas);
  let context = match[0];
  if (Stdlib_Dict.size(context.schemas) === 0) {
    return Pipeline.empty;
  }
  let schemas = Object.values(context.schemas);
  let schemaNameMap = Object.fromEntries(schemas.map(s => [
    s.name,
    s
  ]));
  let allNodes = schemas.map(s => s.name);
  let edges = schemas.flatMap(schema => {
    let references = extractReferencedSchemaNames(schema.type_).filter(name => {
      if (name in schemaNameMap) {
        return name !== schema.name;
      } else {
        return false;
      }
    });
    return references.map(dep => [
      schema.name,
      dep
    ]);
  });
  let sortedNames;
  try {
    sortedNames = Toposort.sortArray(allNodes, edges).toReversed();
  } catch (exn) {
    let visited = {};
    let inStack = {};
    let cycleEdges = [];
    let dfs = node => {
      if (Stdlib_Option.getOr(inStack[node], false) || Stdlib_Option.getOr(visited[node], false)) {
        return;
      } else {
        visited[node] = true;
        inStack[node] = true;
        edges.forEach(param => {
          let from = param[0];
          if (from !== node) {
            return;
          }
          let to = param[1];
          if (Stdlib_Option.getOr(inStack[to], false)) {
            cycleEdges.push([
              from,
              to
            ]);
            return;
          } else {
            return dfs(to);
          }
        });
        inStack[node] = false;
        return;
      }
    };
    allNodes.forEach(dfs);
    let nonCycleEdges = edges.filter(param => {
      let to = param[1];
      let from = param[0];
      return !cycleEdges.some(param => {
        if (param[0] === from) {
          return param[1] === to;
        } else {
          return false;
        }
      });
    });
    try {
      sortedNames = Toposort.sortArray(allNodes, nonCycleEdges).toReversed();
    } catch (exn$1) {
      sortedNames = allNodes.toSorted(Primitive_string.compare);
    }
  }
  let finalSortedSchemas = Stdlib_Array.filterMap(sortedNames, name => schemaNameMap[name]);
  let availableSchemaNames = finalSortedSchemas.map(s => s.name);
  let warnings = match[1].slice();
  let selfRefSchemas = {};
  finalSortedSchemas.forEach(schema => {
    let refs = extractReferencedSchemaNames(schema.type_);
    if (refs.some(name => name === schema.name)) {
      selfRefSchemas[schema.name] = true;
      return;
    }
  });
  let moduleCodes = finalSortedSchemas.map(schema => {
    let isSelfRef = Stdlib_Option.getOr(selfRefSchemas[schema.name], false);
    let selfRefName = isSelfRef ? schema.name : undefined;
    let typeCtx = GenerationContext.make(`ComponentSchemas.` + schema.name, true, availableSchemaNames, undefined, selfRefName, undefined);
    let typeCode = IRToTypeGenerator.generateTypeWithContext(typeCtx, 0, undefined, schema.type_);
    let processed = 0;
    while (processed < typeCtx.extractedTypes.length) {
      let idx = processed;
      let match = typeCtx.extractedTypes[idx];
      let irType = match.irType;
      if (match.isUnboxed && typeof irType === "object" && irType.TAG === "Union") {
        irType._0.forEach(memberType => {
          IRToTypeGenerator.generateTypeWithContext(typeCtx, 0, true, memberType);
        });
      } else {
        IRToTypeGenerator.generateTypeWithContext(typeCtx, 0, false, irType);
      }
      processed = idx + 1 | 0;
    };
    let allExtracted = typeCtx.extractedTypes.slice().toReversed();
    let extractedTypeMap = allExtracted.length !== 0 ? allExtracted : undefined;
    let schemaCtx = GenerationContext.make(`ComponentSchemas.` + schema.name, true, availableSchemaNames, undefined, selfRefName, undefined);
    let schemaCode = IRToSuryGenerator.generateSchemaWithContext(schemaCtx, 0, extractedTypeMap, schema.type_);
    warnings.push(...typeCtx.warnings);
    warnings.push(...schemaCtx.warnings);
    let extractedTypeDefs = allExtracted.map(param => {
      let irType = param.irType;
      let typeName = param.typeName;
      let auxTypeCode;
      if (param.isUnboxed) {
        let exit = 0;
        if (typeof irType !== "object" || irType.TAG !== "Union") {
          exit = 1;
        } else {
          let body = IRToTypeGenerator.generateUnboxedVariantBody(typeCtx, irType._0);
          auxTypeCode = `@unboxed type ` + typeName + ` = ` + body;
        }
        if (exit === 1) {
          let auxType = IRToTypeGenerator.generateTypeWithContext(typeCtx, 0, undefined, irType);
          auxTypeCode = `type ` + typeName + ` = ` + auxType;
        }
      } else {
        let auxType$1 = IRToTypeGenerator.generateTypeWithContext(typeCtx, 0, undefined, irType);
        auxTypeCode = `type ` + typeName + ` = ` + auxType$1;
      }
      let auxSchemaCtx = GenerationContext.make(`ComponentSchemas.` + schema.name + `.` + typeName, true, availableSchemaNames, undefined, undefined, undefined);
      let filteredMap = allExtracted.filter(param => param.typeName !== typeName);
      let auxExtractedTypeMap = filteredMap.length !== 0 ? filteredMap : undefined;
      let auxSchema = IRToSuryGenerator.generateSchemaWithContext(auxSchemaCtx, 0, auxExtractedTypeMap, irType);
      return `  ` + auxTypeCode + `\n  let ` + typeName + `Schema = ` + auxSchema;
    });
    let docComment = Stdlib_Option.mapOr(schema.description, "", d => CodegenUtils.generateDocString(undefined, d, undefined));
    let extractedBlock = extractedTypeDefs.length !== 0 ? extractedTypeDefs.join("\n") + "\n" : "";
    let typeKeyword = isSelfRef ? "type rec t" : "type t";
    let finalSchemaCode = isSelfRef ? `S.recursive("` + schema.name + `", schema => ` + schemaCode + `)` : schemaCode;
    return Handlebars.render(Templates.componentSchemaModule, {
      docComment: docComment,
      moduleName: JsConvertCase.toPascalCase(schema.name),
      extractedBlock: extractedBlock,
      typeKeyword: `  ` + typeKeyword,
      typeCode: typeCode,
      schemaCode: finalSchemaCode
    });
  });
  let fileHeader = CodegenUtils.generateFileHeader("Shared component schemas");
  let fileContent = fileHeader + `\n\n` + moduleCodes.join("\n\n");
  return Pipeline.fromFilesAndWarnings([{
      path: FileSystem.makePath(outputDir, "ComponentSchemas.res"),
      content: fileContent
    }], warnings);
}

export {
  extractReferencedSchemaNames,
  generate,
}
/* Toposort Not a pure module */
