// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Templates from "../core/Templates.res.mjs";
import * as Handlebars from "../bindings/Handlebars.res.mjs";
import * as SpecDiffer from "../core/SpecDiffer.res.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_string from "@rescript/runtime/lib/es6/Primitive_string.js";

function formatEndpointName(endpoint) {
  let methodPart = endpoint.method.toUpperCase();
  let operationIdPart = Stdlib_Option.mapOr(endpoint.operationId, "", id => ` (` + id + `)`);
  return methodPart + ` ` + endpoint.path + operationIdPart;
}

function formatTags(tags) {
  return Stdlib_Option.mapOr(tags, "", tagList => {
    if (tagList.length === 0) {
      return "";
    } else {
      return ` [` + tagList.join(", ") + `]`;
    }
  });
}

function generateMarkdownReport(diff, baseName, forkName) {
  let generateSection = (title, items, formatter) => {
    if (items.length === 0) {
      return "";
    } else {
      return `\n### ` + title + `\n\n` + items.map(formatter).join("\n") + `\n`;
    }
  };
  let totalChanges = SpecDiffer.countChanges(diff);
  let breakingChangesText = SpecDiffer.hasBreakingChanges(diff) ? "⚠️ Yes" : "✓ No";
  let summaryLines = [
    `- **Total Changes**: ` + totalChanges.toString(),
    `- **Added Endpoints**: ` + diff.addedEndpoints.length.toString(),
    `- **Removed Endpoints**: ` + diff.removedEndpoints.length.toString(),
    `- **Modified Endpoints**: ` + diff.modifiedEndpoints.length.toString(),
    `- **Added Schemas**: ` + diff.addedSchemas.length.toString(),
    `- **Removed Schemas**: ` + diff.removedSchemas.length.toString(),
    `- **Modified Schemas**: ` + diff.modifiedSchemas.length.toString(),
    `- **Breaking Changes**: ` + breakingChangesText
  ].join("\n");
  let reportParts = [
    `# API Diff Report: ` + baseName + ` → ` + forkName + `\n\n## Summary\n\n` + summaryLines,
    generateSection("Added Endpoints", diff.addedEndpoints, endpoint => {
      let endpointName = formatEndpointName(endpoint);
      let tags = formatTags(endpoint.tags);
      let summary = Stdlib_Option.mapOr(endpoint.summary, "", summary => `\n  ` + summary);
      return `- **` + endpointName + `**` + tags + summary;
    }),
    generateSection("Removed Endpoints", diff.removedEndpoints, endpoint => {
      let endpointName = formatEndpointName(endpoint);
      let tags = formatTags(endpoint.tags);
      return `- **` + endpointName + `**` + tags;
    }),
    generateSection("Modified Endpoints", diff.modifiedEndpoints, endpointDiff => {
      let methodPart = endpointDiff.method.toUpperCase();
      let breakingText = endpointDiff.breakingChange ? " **⚠️ BREAKING**" : "";
      let changes = [
        endpointDiff.requestBodyChanged ? "body" : "",
        endpointDiff.responseChanged ? "response" : ""
      ].filter(x => x !== "").join(", ");
      return `- **` + methodPart + ` ` + endpointDiff.path + `**` + breakingText + `: Changed ` + changes;
    }),
    generateSection("Added Schemas", diff.addedSchemas, schemaName => `- \`` + schemaName + `\``),
    generateSection("Removed Schemas", diff.removedSchemas, schemaName => `- \`` + schemaName + `\``),
    generateSection("Modified Schemas", diff.modifiedSchemas, schemaDiff => {
      let breakingText = schemaDiff.breakingChange ? " **⚠️ BREAKING**" : "";
      return `- \`` + schemaDiff.name + `\`` + breakingText;
    }),
    `\n---\n*Generated on ` + new Date().toISOString() + `*`
  ];
  return reportParts.filter(part => part !== "").join("\n");
}

function generateCompactSummary(diff) {
  let totalChanges = SpecDiffer.countChanges(diff);
  let addedCount = diff.addedEndpoints.length;
  let removedCount = diff.removedEndpoints.length;
  let modifiedCount = diff.modifiedEndpoints.length;
  let breakingText = SpecDiffer.hasBreakingChanges(diff) ? " (BREAKING)" : "";
  return `Found ` + totalChanges.toString() + ` changes: +` + addedCount.toString() + ` -` + removedCount.toString() + ` ~` + modifiedCount.toString() + ` endpoints` + breakingText;
}

function generateMergeReport(stats, baseName, forkName) {
  return Handlebars.render(Templates.mergeReport, {
    baseName: baseName,
    forkName: forkName,
    sharedEndpoints: stats.sharedEndpointCount.toString(),
    sharedSchemas: stats.sharedSchemaCount.toString(),
    extensionEndpoints: stats.forkExtensionCount.toString(),
    extensionSchemas: stats.forkSchemaCount.toString(),
    timestamp: new Date().toISOString()
  });
}

function generateEndpointsByTagReport(endpoints) {
  let endpointsByTag = {};
  let untaggedEndpoints = [];
  endpoints.forEach(endpoint => {
    let tags = endpoint.tags;
    if (tags !== undefined && tags.length !== 0) {
      tags.forEach(tag => {
        let existing = Stdlib_Option.getOr(endpointsByTag[tag], []);
        existing.push(endpoint);
        endpointsByTag[tag] = existing;
      });
    } else {
      untaggedEndpoints.push(endpoint);
    }
  });
  let tagSections = Object.keys(endpointsByTag).toSorted(Primitive_string.compare).map(tag => {
    let tagEndpoints = Stdlib_Option.getOr(endpointsByTag[tag], []);
    let count = tagEndpoints.length.toString();
    let endpointList = tagEndpoints.map(endpoint => `- ` + formatEndpointName(endpoint)).join("\n");
    return `### ` + tag + ` (` + count + `)\n\n` + endpointList;
  }).join("\n\n");
  let untaggedSection;
  if (untaggedEndpoints.length !== 0) {
    let count = untaggedEndpoints.length.toString();
    let endpointList = untaggedEndpoints.map(endpoint => `- ` + formatEndpointName(endpoint)).join("\n");
    untaggedSection = `\n\n### Untagged (` + count + `)\n\n` + endpointList;
  } else {
    untaggedSection = "";
  }
  return `## Endpoints by Tag\n\n` + tagSections + untaggedSection;
}

export {
  formatEndpointName,
  formatTags,
  generateMarkdownReport,
  generateCompactSummary,
  generateMergeReport,
  generateEndpointsByTagReport,
}
/* Handlebars Not a pure module */
