// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Templates from "../core/Templates.res.mjs";
import * as Handlebars from "../bindings/Handlebars.res.mjs";
import * as DocOverride from "../core/DocOverride.res.mjs";
import * as CodegenUtils from "../core/CodegenUtils.res.mjs";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as SchemaIRParser from "../core/SchemaIRParser.res.mjs";
import * as JsConvertCase from "js-convert-case";
import * as IRToSuryGenerator from "./IRToSuryGenerator.res.mjs";
import * as IRToTypeGenerator from "./IRToTypeGenerator.res.mjs";

function getJsonSchemaFromRequestBody(requestBody) {
  return Stdlib_Option.flatMap(requestBody, body => Stdlib_Option.flatMap(Object.entries(body.content)[0], param => param[1].schema));
}

function generateTypeCodeAndSchemaCode(jsonSchema, typeName, schemaName, modulePrefixOpt) {
  let modulePrefix = modulePrefixOpt !== undefined ? modulePrefixOpt : "";
  let match = SchemaIRParser.parseJsonSchema(undefined, jsonSchema);
  let ir = match[0];
  let match$1 = IRToTypeGenerator.generateNamedType({
    name: typeName,
    description: jsonSchema.description,
    type_: ir
  }, undefined, undefined, modulePrefix);
  let match$2 = IRToSuryGenerator.generateNamedSchema({
    name: schemaName,
    description: jsonSchema.description,
    type_: ir
  }, undefined, undefined, modulePrefix, match$1[2]);
  return [
    match$1[0],
    match$2[0]
  ];
}

function generateEndpointFunction(endpoint, overrideDir, moduleName) {
  let functionName = CodegenUtils.generateOperationName(endpoint.operationId, endpoint.path, endpoint.method);
  let requestTypeName = functionName + `Request`;
  let hasRequestBody = Stdlib_Option.isSome(endpoint.requestBody);
  let requestBody = Stdlib_Option.getOr(endpoint.requestBody, {
    description: undefined,
    content: {},
    required: false
  });
  let isRequestBodyRequired = Stdlib_Option.getOr(requestBody.required, false);
  let bodyParam = hasRequestBody ? (
      isRequestBodyRequired ? `~body: ` + requestTypeName : `~body: option<` + requestTypeName + `>=?`
    ) : "";
  let paramSep = hasRequestBody ? ", " : "";
  let bodyValueConversion = hasRequestBody ? (
      isRequestBodyRequired ? `  let jsonBody = body->S.reverseConvertToJsonOrThrow(` + functionName + `RequestSchema)` : `  let jsonBody = body->Option.map(b => b->S.reverseConvertToJsonOrThrow(` + functionName + `RequestSchema))`
    ) : "";
  let successResponse = Stdlib_Array.filterMap([
      "200",
      "201",
      "202",
      "204"
    ], code => endpoint.responses[code])[0];
  let responseHandling = Stdlib_Option.mapOr(successResponse, "  response", response => Stdlib_Option.mapOr(response.content, "  let _ = response", content => {
    if (Object.entries(content).length !== 0) {
      return `  response->S.parseOrThrow(` + functionName + `ResponseSchema)`;
    } else {
      return "  response";
    }
  }));
  let description;
  if (overrideDir !== undefined && moduleName !== undefined) {
    let overrideResult = DocOverride.readOverrideWithValidation(overrideDir, moduleName, functionName, DocOverride.generateEndpointHash(endpoint));
    if (typeof overrideResult !== "object") {
      description = endpoint.description;
    } else {
      switch (overrideResult.TAG) {
        case "ValidOverride" :
          description = overrideResult._0;
          break;
        case "InvalidHash" :
          description = overrideResult.override;
          break;
        case "FileError" :
          description = endpoint.description;
          break;
      }
    }
  } else {
    description = endpoint.description;
  }
  let docComment = CodegenUtils.generateDocString(endpoint.summary, description, undefined);
  return Handlebars.render(Templates.endpointFunction, {
    docComment: docComment,
    functionName: functionName,
    bodyParam: bodyParam,
    paramSep: paramSep,
    fetchTypeSignature: CodegenUtils.fetchTypeSignature,
    bodyValueConversion: bodyValueConversion,
    path: endpoint.path,
    methodUpper: endpoint.method.toUpperCase(),
    bodyArg: hasRequestBody ? "Some(jsonBody)" : "None",
    responseHandling: responseHandling
  });
}

function generateEndpointCode(endpoint, overrideDir, moduleName, modulePrefixOpt) {
  let modulePrefix = modulePrefixOpt !== undefined ? modulePrefixOpt : "";
  let functionName = CodegenUtils.generateOperationName(endpoint.operationId, endpoint.path, endpoint.method);
  let requestJsonSchema = getJsonSchemaFromRequestBody(endpoint.requestBody);
  let responseJsonSchema = Stdlib_Option.flatMap(Stdlib_Option.flatMap(Stdlib_Array.filterMap([
      "200",
      "201",
      "202",
      "204"
    ], code => endpoint.responses[code])[0], resp => resp.content), content => Stdlib_Option.flatMap(Object.entries(content)[0], param => param[1].schema));
  let requestPart = Stdlib_Option.mapOr(requestJsonSchema, "", schema => {
    let match = generateTypeCodeAndSchemaCode(schema, functionName + `Request`, functionName + `Request`, modulePrefix);
    return match[0] + `\n\n` + match[1];
  });
  let responsePart = Stdlib_Option.mapOr(responseJsonSchema, `type ` + functionName + `Response = unit`, schema => {
    let match = generateTypeCodeAndSchemaCode(schema, functionName + `Response`, functionName + `Response`, modulePrefix);
    return match[0] + `\n\n` + match[1];
  });
  return [
    requestPart,
    responsePart,
    generateEndpointFunction(endpoint, overrideDir, moduleName)
  ].filter(s => s !== "").join("\n\n");
}

function generateEndpointModule(endpoint, modulePrefixOpt) {
  let modulePrefix = modulePrefixOpt !== undefined ? modulePrefixOpt : "";
  let functionName = CodegenUtils.generateOperationName(endpoint.operationId, endpoint.path, endpoint.method);
  let header = CodegenUtils.generateFileHeader(Stdlib_Option.getOr(endpoint.summary, `API: ` + endpoint.path));
  return Handlebars.render(Templates.moduleWrapped, {
    header: header.trimEnd(),
    moduleName: JsConvertCase.toPascalCase(functionName),
    body: CodegenUtils.indent(generateEndpointCode(endpoint, undefined, undefined, modulePrefix), 2)
  });
}

function generateEndpointsModule(moduleName, endpoints, description, overrideDir, modulePrefixOpt) {
  let modulePrefix = modulePrefixOpt !== undefined ? modulePrefixOpt : "";
  let header = CodegenUtils.generateFileHeader(Stdlib_Option.getOr(description, `API for ` + moduleName));
  let body = endpoints.map(ep => CodegenUtils.indent(generateEndpointCode(ep, overrideDir, moduleName, modulePrefix), 2)).join("\n\n");
  return Handlebars.render(Templates.moduleWrapped, {
    header: header.trimEnd(),
    moduleName: moduleName,
    body: body
  });
}

function generateEndpointSignature(endpoint) {
  let functionName = CodegenUtils.generateOperationName(endpoint.operationId, endpoint.path, endpoint.method);
  let summaryPrefix = Stdlib_Option.mapOr(endpoint.summary, "", s => `// ` + s + `\n`);
  let bodyParam = Stdlib_Option.isSome(endpoint.requestBody) ? "~body: 'body, " : "";
  return summaryPrefix + `let ` + functionName + `: (` + bodyParam + `~fetch: fetchFn) => promise<` + functionName + `Response>`;
}

export {
  getJsonSchemaFromRequestBody,
  generateTypeCodeAndSchemaCode,
  generateEndpointFunction,
  generateEndpointCode,
  generateEndpointModule,
  generateEndpointsModule,
  generateEndpointSignature,
}
/* Handlebars Not a pure module */
