// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as SchemaIRParser from "../core/SchemaIRParser.res.mjs";
import * as JsConvertCase from "js-convert-case";

function generateType(_irType, _isOptionalOpt) {
  while (true) {
    let isOptionalOpt = _isOptionalOpt;
    let irType = _irType;
    let isOptional = isOptionalOpt !== undefined ? isOptionalOpt : false;
    if (typeof irType !== "object") {
      switch (irType) {
        case "Boolean" :
          return "boolean";
        case "Null" :
          return "null";
        case "Unknown" :
          return "unknown";
      }
    } else {
      switch (irType.TAG) {
        case "String" :
          return "string";
        case "Number" :
        case "Integer" :
          return "number";
        case "Array" :
          return generateType(irType.items, undefined) + `[]`;
        case "Object" :
          return generateObjectType(irType.properties, irType.additionalProperties);
        case "Literal" :
          let literal = irType._0;
          if (typeof literal !== "object") {
            return "null";
          }
          switch (literal.TAG) {
            case "StringLiteral" :
              return `"` + literal._0 + `"`;
            case "NumberLiteral" :
              return literal._0.toString();
            case "BooleanLiteral" :
              if (literal._0) {
                return "true";
              } else {
                return "false";
              }
          }
        case "Union" :
          return irType._0.map(t => generateType(t, undefined)).join(" | ");
        case "Intersection" :
          return irType._0.map(t => generateType(t, undefined)).join(" & ");
        case "Reference" :
          let ref = irType._0;
          let match = ref.split("/");
          if (match.length !== 4) {
            return ref;
          }
          let match$1 = match[1];
          if (match$1 !== "components") {
            return ref;
          }
          let match$2 = match[2];
          if (match$2 !== "schemas") {
            return ref;
          }
          let name = match[3];
          return `ComponentSchemas.` + name;
        case "Option" :
          let inner = irType._0;
          if (!isOptional) {
            return generateType(inner, undefined) + ` | undefined`;
          }
          _isOptionalOpt = true;
          _irType = inner;
          continue;
      }
    }
  };
}

function generateObjectType(properties, additionalProperties) {
  let propertyLines = properties.map(param => {
    let isRequired = param[2];
    let fieldType = param[1];
    let match;
    match = typeof fieldType !== "object" ? [
        fieldType,
        !isRequired
      ] : (
        fieldType.TAG === "Option" ? [
            fieldType._0,
            true
          ] : [
            fieldType,
            !isRequired
          ]
      );
    return `  ` + param[0] + (
      match[1] ? "?" : ""
    ) + `: ` + generateType(match[0], true) + `;`;
  });
  let additionalPropertiesLines = Stdlib_Option.mapOr(additionalProperties, [], valueType => [`  [key: string]: ` + generateType(valueType, undefined) + `;`]);
  let allLines = propertyLines.concat(additionalPropertiesLines);
  if (allLines.length === 0) {
    return "Record<string, never>";
  } else {
    return `{\n` + allLines.join("\n") + `\n}`;
  }
}

function generateNamedType(namedSchema) {
  let docComment = Stdlib_Option.mapOr(namedSchema.description, "", description => `/** ` + description + ` */\n`);
  let typeCode = generateType(namedSchema.type_, undefined);
  let match = namedSchema.type_;
  let declaration;
  let exit = 0;
  if (typeof match !== "object" || match.TAG !== "Object") {
    exit = 1;
  } else {
    declaration = typeCode === "Record<string, never>" ? `export type ` + namedSchema.name + ` = ` + typeCode + `;` : `export interface ` + namedSchema.name + ` ` + typeCode;
  }
  if (exit === 1) {
    declaration = `export type ` + namedSchema.name + ` = ` + typeCode + `;`;
  }
  return docComment + declaration;
}

function generateParameterType(name, schema) {
  let match = SchemaIRParser.parseJsonSchema(undefined, schema);
  return [
    JsConvertCase.toCamelCase(name),
    generateType(match[0], undefined)
  ];
}

export {
  generateType,
  generateObjectType,
  generateNamedType,
  generateParameterType,
}
/* js-convert-case Not a pure module */
