// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Pipeline from "../core/Pipeline.res.mjs";
import * as Templates from "../core/Templates.res.mjs";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as FileSystem from "../core/FileSystem.res.mjs";
import * as Handlebars from "../bindings/Handlebars.res.mjs";
import * as CodegenUtils from "../core/CodegenUtils.res.mjs";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as OpenAPIParser from "../core/OpenAPIParser.res.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as SchemaIRParser from "../core/SchemaIRParser.res.mjs";
import * as JsConvertCase from "js-convert-case";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as Primitive_string from "@rescript/runtime/lib/es6/Primitive_string.js";
import * as EndpointGenerator from "./EndpointGenerator.res.mjs";
import * as IRToSuryGenerator from "./IRToSuryGenerator.res.mjs";
import * as IRToTypeGenerator from "./IRToTypeGenerator.res.mjs";
import * as ComponentSchemaGenerator from "./ComponentSchemaGenerator.res.mjs";

function generateSchemaCodeForDict(schemaDict) {
  return Object.entries(schemaDict).toSorted((param, param$1) => Primitive_string.compare(param[0], param$1[0])).flatMap(param => {
    let schema = param[1];
    let name = param[0];
    let match = SchemaIRParser.parseJsonSchema(undefined, schema);
    let ir = match[0];
    let match$1 = IRToTypeGenerator.generateNamedType({
      name: name,
      description: schema.description,
      type_: ir
    }, undefined, undefined, undefined);
    let match$2 = IRToSuryGenerator.generateNamedSchema({
      name: name + `Schema`,
      description: schema.description,
      type_: ir
    }, undefined, undefined, undefined, match$1[2]);
    return [
      CodegenUtils.indent(match$1[0], 2),
      CodegenUtils.indent(match$2[0], 2),
      ""
    ];
  });
}

function generateTagModulesCode(endpoints, overrideDir, indentOpt) {
  let indent = indentOpt !== undefined ? indentOpt : 2;
  let groupedByTag = OpenAPIParser.groupByTag(endpoints);
  let indentStr = " ".repeat(indent);
  return Stdlib_Array.filterMap(Object.keys(groupedByTag).toSorted(Primitive_string.compare), tag => Stdlib_Option.map(groupedByTag[tag], tagEndpoints => {
    let moduleName = JsConvertCase.toPascalCase(tag);
    let endpointLines = tagEndpoints.flatMap(endpoint => [
      CodegenUtils.indent(EndpointGenerator.generateEndpointCode(endpoint, overrideDir, moduleName, undefined), indent + 2 | 0),
      ""
    ]);
    return [indentStr + `module ` + moduleName + ` = {`].concat(endpointLines.concat([
      indentStr + `}`,
      ""
    ]));
  })).flatMap(lines => lines);
}

function generateTagModuleFile(tag, endpoints, $staropt$star, $staropt$star$1, overrideDir) {
  if ($staropt$star === undefined) {
    true;
  }
  let wrapInModule = $staropt$star$1 !== undefined ? $staropt$star$1 : false;
  let moduleName = JsConvertCase.toPascalCase(tag);
  let header = CodegenUtils.generateFileHeader(`API endpoints for ` + tag);
  let body = endpoints.map(endpoint => EndpointGenerator.generateEndpointCode(endpoint, overrideDir, moduleName, undefined)).join("\n\n");
  if (wrapInModule) {
    return Handlebars.render(Templates.moduleWrapped, {
      header: header.trimEnd(),
      moduleName: moduleName,
      body: CodegenUtils.indent(body, 2)
    });
  } else {
    return Handlebars.render(Templates.moduleUnwrapped, {
      header: header.trimEnd(),
      body: body
    });
  }
}

function generateAllTagModules(endpoints, includeSchemasOpt, wrapInModuleOpt, overrideDir) {
  let includeSchemas = includeSchemasOpt !== undefined ? includeSchemasOpt : true;
  let wrapInModule = wrapInModuleOpt !== undefined ? wrapInModuleOpt : false;
  let groupedByTag = OpenAPIParser.groupByTag(endpoints);
  return Object.entries(groupedByTag).toSorted((param, param$1) => Primitive_string.compare(param[0], param$1[0])).map(param => {
    let tag = param[0];
    return [
      tag,
      generateTagModuleFile(tag, param[1], includeSchemas, wrapInModule, overrideDir)
    ];
  });
}

function generateIndexModule(tags, moduleNameOpt) {
  let moduleName = moduleNameOpt !== undefined ? moduleNameOpt : "API";
  let header = CodegenUtils.generateFileHeader("Main API module index");
  let tagData = tags.toSorted(Primitive_string.compare).map(tag => ({
    modulePascal: JsConvertCase.toPascalCase(tag)
  }));
  return Handlebars.render(Templates.indexModule, {
    header: header.trimEnd(),
    moduleName: moduleName,
    tags: tagData
  });
}

function generateFlatModuleCode(moduleName, endpoints, overrideDir) {
  let header = CodegenUtils.generateFileHeader(`All API endpoints in ` + moduleName);
  let body = endpoints.map(endpoint => CodegenUtils.indent(EndpointGenerator.generateEndpointCode(endpoint, overrideDir, moduleName, undefined), 2)).join("\n\n");
  return Handlebars.render(Templates.moduleWrapped, {
    header: header.trimEnd(),
    moduleName: moduleName,
    body: body
  });
}

function internalGenerateIntegratedModule(name, description, endpoints, schemas, overrideDir, isExtensionOpt, includeHeaderOpt) {
  let isExtension = isExtensionOpt !== undefined ? isExtensionOpt : false;
  let includeHeader = includeHeaderOpt !== undefined ? includeHeaderOpt : true;
  let lines = [];
  if (includeHeader) {
    lines.push(CodegenUtils.generateFileHeader(description), "");
  }
  lines.push(`module ` + name + ` = {`);
  Stdlib_Option.forEach(schemas, schemaDict => {
    if (Object.keys(schemaDict).length !== 0) {
      lines.push(...Belt_Array.concatMany([
        [
          `  // ` + (
            isExtension ? "Extension" : "Component"
          ) + ` Schemas`,
          ""
        ],
        generateSchemaCodeForDict(schemaDict)
      ]));
      return;
    }
  });
  if (endpoints.length !== 0) {
    if (isExtension) {
      lines.push("  // Extension Endpoints", "");
    }
    lines.push(...generateTagModulesCode(endpoints, overrideDir, undefined));
  }
  lines.push("}");
  return lines.join("\n");
}

function generateSharedModule(endpoints, schemas, overrideDir, includeHeaderOpt) {
  let includeHeader = includeHeaderOpt !== undefined ? includeHeaderOpt : true;
  return internalGenerateIntegratedModule("Shared", "Shared API code", endpoints, schemas, overrideDir, undefined, includeHeader);
}

function generateExtensionModule(forkName, endpoints, schemas, overrideDir, includeHeaderOpt) {
  let includeHeader = includeHeaderOpt !== undefined ? includeHeaderOpt : true;
  return internalGenerateIntegratedModule(JsConvertCase.toPascalCase(forkName) + `Extensions`, forkName + ` extensions`, endpoints, schemas, overrideDir, true, includeHeader);
}

function generateCombinedModule(forkName, sharedEndpoints, extensionEndpoints, sharedSchemas, extensionSchemas, overrideDir) {
  let header = CodegenUtils.generateFileHeader(`Combined Shared and ` + forkName + ` extensions`);
  let shared = generateSharedModule(sharedEndpoints, sharedSchemas, overrideDir, false);
  let extension = generateExtensionModule(forkName, extensionEndpoints, extensionSchemas, overrideDir, false);
  return Handlebars.render(Templates.combinedModule, {
    header: header.trimEnd(),
    shared: shared,
    extension: extension
  });
}

function generateTagModuleFiles(endpoints, outputDir, wrapInModuleOpt, overrideDir) {
  let wrapInModule = wrapInModuleOpt !== undefined ? wrapInModuleOpt : false;
  let files = generateAllTagModules(endpoints, true, wrapInModule, overrideDir).map(param => {
    let path = FileSystem.makePath(outputDir, JsConvertCase.toPascalCase(param[0]) + `.res`);
    return {
      path: path,
      content: param[1]
    };
  });
  return Pipeline.fromFilesAndWarnings(files, []);
}

function generateFlatModuleFile(moduleName, endpoints, outputDir, overrideDir) {
  let path = FileSystem.makePath(outputDir, moduleName + `.res`);
  let content = generateFlatModuleCode(moduleName, endpoints, overrideDir);
  return Pipeline.fromFile({
    path: path,
    content: content
  });
}

function generateInstanceTagModules(instanceName, modulePrefix, endpoints, schemas, outputDir, overrideDir) {
  let apiDir = FileSystem.makePath(FileSystem.makePath(outputDir, instanceName), "api");
  let schemaFiles = Stdlib_Option.mapOr(schemas, [], schemaDict => {
    if (Object.keys(schemaDict).length === 0) {
      return [];
    }
    let result = ComponentSchemaGenerator.generate({
      openapi: "3.1.0",
      info: {
        title: instanceName,
        version: "1.0.0",
        description: undefined
      },
      paths: {},
      components: {
        schemas: schemaDict
      }
    }, apiDir);
    return result.files.map(file => {
      if (file.path.endsWith("ComponentSchemas.res")) {
        return {
          path: file.path.replace("ComponentSchemas.res", modulePrefix + `ComponentSchemas.res`),
          content: file.content
        };
      } else {
        return file;
      }
    });
  });
  let groupedByTag = OpenAPIParser.groupByTag(endpoints);
  let endpointFiles = Stdlib_Array.filterMap(Object.entries(groupedByTag).toSorted((param, param$1) => Primitive_string.compare(param[0], param$1[0])), param => {
    let tag = param[0];
    let moduleName = modulePrefix + JsConvertCase.toPascalCase(tag);
    let endpointCodes = param[1].flatMap(endpoint => [
      EndpointGenerator.generateEndpointCode(endpoint, overrideDir, moduleName, modulePrefix),
      ""
    ]);
    let content = Belt_Array.concatMany([
      [
        CodegenUtils.generateFileHeader(instanceName + ` API for ` + tag),
        ""
      ],
      endpointCodes
    ]).join("\n");
    let path = FileSystem.makePath(apiDir, moduleName + `.res`);
    return {
      path: path,
      content: content
    };
  });
  return Pipeline.fromFilesAndWarnings(schemaFiles.concat(endpointFiles), []);
}

let generateBaseTagModules = generateInstanceTagModules;

let generateForkTagModules = generateInstanceTagModules;

function generateSeparatePerTagModules(baseName, basePrefix, forkName, forkPrefixOpt, sharedEndpoints, extensionEndpoints, sharedSchemas, extensionSchemas, outputDir, overrideDir) {
  let forkPrefix = forkPrefixOpt !== undefined ? Primitive_option.valFromOption(forkPrefixOpt) : undefined;
  return Pipeline.combine([
    generateBaseTagModules(baseName, basePrefix, sharedEndpoints, sharedSchemas, outputDir, overrideDir),
    generateForkTagModules(forkName, Stdlib_Option.getOr(forkPrefix, JsConvertCase.toPascalCase(forkName)), extensionEndpoints, extensionSchemas, outputDir, overrideDir)
  ]);
}

export {
  generateSchemaCodeForDict,
  generateTagModulesCode,
  generateTagModuleFile,
  generateAllTagModules,
  generateIndexModule,
  generateFlatModuleCode,
  internalGenerateIntegratedModule,
  generateSharedModule,
  generateExtensionModule,
  generateCombinedModule,
  generateTagModuleFiles,
  generateFlatModuleFile,
  generateInstanceTagModules,
  generateBaseTagModules,
  generateForkTagModules,
  generateSeparatePerTagModules,
}
/* FileSystem Not a pure module */
