// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Templates from "../core/Templates.res.mjs";
import * as Handlebars from "../bindings/Handlebars.res.mjs";
import * as CodegenUtils from "../core/CodegenUtils.res.mjs";
import * as OpenAPIParser from "../core/OpenAPIParser.res.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as SchemaIRParser from "../core/SchemaIRParser.res.mjs";
import * as JsConvertCase from "js-convert-case";
import * as IRToSuryGenerator from "./IRToSuryGenerator.res.mjs";
import * as IRToTypeGenerator from "./IRToTypeGenerator.res.mjs";

function generateTypeCodeAndSchemaCode(name, schema) {
  let match = SchemaIRParser.parseJsonSchema(undefined, schema);
  let ir = match[0];
  let match$1 = IRToTypeGenerator.generateNamedType({
    name: name,
    description: schema.description,
    type_: ir
  }, undefined, undefined, undefined);
  let match$2 = IRToSuryGenerator.generateNamedSchema({
    name: name + `Schema`,
    description: schema.description,
    type_: ir
  }, undefined, undefined, undefined, match$1[2]);
  return match$1[0] + `\n\n` + match$2[0];
}

let generateTypeAndSchema = generateTypeCodeAndSchemaCode;

function generateComponentSchemas(components) {
  return Stdlib_Option.mapOr(Stdlib_Option.flatMap(components, c => c.schemas), "// No component schemas\n", schemas => {
    let sections = Object.entries(schemas).map(param => generateTypeCodeAndSchemaCode(param[0], param[1])).join("\n\n");
    return `// Component Schemas\n\n` + sections;
  });
}

function generateOperationSchemas(operationId, operation) {
  let generatePart = (suffix, schemaOpt) => Stdlib_Option.mapOr(schemaOpt, "", schema => generateTypeCodeAndSchemaCode(JsConvertCase.toPascalCase(operationId) + suffix, schema));
  let requestBodySchema = Stdlib_Option.flatMap(Stdlib_Option.flatMap(operation.requestBody, body => body.content["application/json"]), mediaType => mediaType.schema);
  let responses = operation.responses;
  let successResponseSchema = Stdlib_Option.flatMap(Stdlib_Option.flatMap(Stdlib_Option.flatMap(Stdlib_Option.orElse(responses["200"], responses["201"]), response => response.content), content => content["application/json"]), mediaType => mediaType.schema);
  return [
    generatePart("Request", requestBodySchema),
    generatePart("Response", successResponseSchema)
  ].filter(code => code !== "").join("\n\n");
}

function generateEndpointModule(path, method, operation) {
  let operationId = OpenAPIParser.getOperationId(path, method, operation);
  let docComment = CodegenUtils.generateDocComment(operation.summary, operation.description, undefined);
  let methodStr = method === "GET" ? "GET" : (
      method === "PUT" ? "PUT" : (
          method === "DELETE" ? "DELETE" : (
              method === "HEAD" ? "HEAD" : (
                  method === "POST" ? "POST" : (
                      method === "PATCH" ? "PATCH" : "OPTIONS"
                    )
                )
            )
        )
    );
  let schemasCode = generateOperationSchemas(operationId, operation);
  return Handlebars.render(Templates.endpointModule, {
    docComment: docComment,
    moduleName: JsConvertCase.toPascalCase(operationId),
    schemasCode: CodegenUtils.indent(schemasCode, 2),
    path: path,
    methodStr: methodStr
  });
}

export {
  generateTypeCodeAndSchemaCode,
  generateTypeAndSchema,
  generateComponentSchemas,
  generateOperationSchemas,
  generateEndpointModule,
}
/* Handlebars Not a pure module */
