// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Pipeline from "../core/Pipeline.res.mjs";
import * as Templates from "../core/Templates.res.mjs";
import * as FileSystem from "../core/FileSystem.res.mjs";
import * as Handlebars from "../bindings/Handlebars.res.mjs";
import * as CodegenUtils from "../core/CodegenUtils.res.mjs";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as OpenAPIParser from "../core/OpenAPIParser.res.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as JsConvertCase from "js-convert-case";

let clientTypeCode = Handlebars.render(Templates.clientType, {
  fetchTypeSignature: CodegenUtils.fetchTypeSignature
});

function generateConnectFunction(title) {
  return Handlebars.render(Templates.connectFunction, {
    title: title,
    fetchTypeSignature: CodegenUtils.fetchTypeSignature
  });
}

function generateWrapperFunction(endpoint, generatedModuleName) {
  let operationName = CodegenUtils.generateOperationName(endpoint.operationId, endpoint.path, endpoint.method);
  let hasRequestBody = Stdlib_Option.isSome(endpoint.requestBody);
  let docComment = Stdlib_Option.mapOr(endpoint.summary, "", summary => {
    let descriptionPart = Stdlib_Option.mapOr(endpoint.description, "", description => {
      if (description === summary) {
        return "";
      } else {
        return " - " + description;
      }
    });
    return `  /** ` + summary + descriptionPart + ` */\n`;
  });
  let signature = hasRequestBody ? `let ` + operationName + ` = (request: ` + generatedModuleName + `.` + operationName + `Request, ~client: client)` : `let ` + operationName + ` = (~client: client)`;
  let callArguments = hasRequestBody ? "~body=request, " : "";
  return Handlebars.render(Templates.wrapperFunction, {
    docComment: docComment,
    signature: signature,
    generatedModuleName: generatedModuleName,
    operationName: operationName,
    callArguments: callArguments
  });
}

function generateWrapper(spec, endpoints, extensionEndpointsOpt, outputDir, wrapperModuleNameOpt, generatedModulePrefixOpt, baseModulePrefixOpt) {
  let extensionEndpoints = extensionEndpointsOpt !== undefined ? extensionEndpointsOpt : [];
  let wrapperModuleName = wrapperModuleNameOpt !== undefined ? wrapperModuleNameOpt : "Wrapper";
  let generatedModulePrefix = generatedModulePrefixOpt !== undefined ? generatedModulePrefixOpt : "";
  let baseModulePrefix = baseModulePrefixOpt !== undefined ? baseModulePrefixOpt : "";
  let extensionOperationIds = Stdlib_Array.reduce(extensionEndpoints, {}, (acc, endpoint) => {
    let name = CodegenUtils.generateOperationName(endpoint.operationId, endpoint.path, endpoint.method);
    acc[name] = true;
    return acc;
  });
  let hasExtensions = extensionEndpoints.length !== 0;
  let allEndpoints = (
    hasExtensions ? endpoints.filter(endpoint => {
        let name = CodegenUtils.generateOperationName(endpoint.operationId, endpoint.path, endpoint.method);
        return !(name in extensionOperationIds);
      }) : endpoints
  ).concat(extensionEndpoints);
  let endpointsByTag = OpenAPIParser.groupByTag(allEndpoints);
  let modulesCode = Object.keys(endpointsByTag).map(tag => {
    let moduleName = JsConvertCase.toPascalCase(tag);
    let wrapperFunctions = Stdlib_Option.getOr(endpointsByTag[tag], []).map(endpoint => {
      let operationName = CodegenUtils.generateOperationName(endpoint.operationId, endpoint.path, endpoint.method);
      let isExtension = hasExtensions && operationName in extensionOperationIds;
      let prefix = !isExtension && baseModulePrefix !== "" ? baseModulePrefix : generatedModulePrefix;
      let targetModuleName = prefix !== "" ? prefix + moduleName : moduleName;
      return generateWrapperFunction(endpoint, targetModuleName);
    }).join("\n\n");
    return `module ` + moduleName + ` = {\n` + wrapperFunctions + `\n}`;
  }).join("\n\n");
  let fileContent = Handlebars.render(Templates.wrapperFile, {
    clientTypeCode: clientTypeCode,
    connectFunctionCode: generateConnectFunction(spec.info.title),
    modulesCode: modulesCode
  });
  return Pipeline.fromFilesAndWarnings([{
      path: FileSystem.makePath(outputDir, wrapperModuleName + `.res`),
      content: fileContent
    }], []);
}

export {
  clientTypeCode,
  generateConnectFunction,
  generateWrapperFunction,
  generateWrapper,
}
/* clientTypeCode Not a pure module */
