// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Templates from "../core/Templates.res.mjs";
import * as FileSystem from "../core/FileSystem.res.mjs";
import * as Handlebars from "../bindings/Handlebars.res.mjs";
import * as CodegenUtils from "../core/CodegenUtils.res.mjs";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as OpenAPIParser from "../core/OpenAPIParser.res.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as SchemaIRParser from "../core/SchemaIRParser.res.mjs";
import * as JsConvertCase from "js-convert-case";
import * as IRToTypeScriptGenerator from "./IRToTypeScriptGenerator.res.mjs";

function getFirstJsonSchema(contentDict) {
  return Stdlib_Option.flatMap(Stdlib_Option.flatMap(Object.keys(contentDict)[0], contentType => contentDict[contentType]), mediaType => mediaType.schema);
}

function generateTypeScriptType(name, description, schema) {
  let match = SchemaIRParser.parseJsonSchema(undefined, schema);
  return IRToTypeScriptGenerator.generateNamedType({
    name: name,
    description: description,
    type_: match[0]
  });
}

function generateRequestInterface(endpoint, functionName) {
  let requestTypeName = JsConvertCase.toPascalCase(functionName) + `Request`;
  return Stdlib_Option.flatMap(endpoint.requestBody, body => Stdlib_Option.map(getFirstJsonSchema(body.content), schema => generateTypeScriptType(requestTypeName, body.description, schema)));
}

function generateResponseInterface(endpoint, functionName) {
  let responseTypeName = JsConvertCase.toPascalCase(functionName) + `Response`;
  let successCodes = [
    "200",
    "201",
    "202",
    "204"
  ];
  let successResponse = Stdlib_Array.filterMap(successCodes, code => endpoint.responses[code])[0];
  return Stdlib_Option.getOr(Stdlib_Option.flatMap(successResponse, response => Stdlib_Option.map(Stdlib_Option.flatMap(response.content, getFirstJsonSchema), schema => generateTypeScriptType(responseTypeName, response.description, schema))), `export type ` + responseTypeName + ` = void;`);
}

function generateMethodSignature(endpoint, functionName) {
  let params = Stdlib_Option.isSome(endpoint.requestBody) ? `client: MisskeyClient, request: ` + JsConvertCase.toPascalCase(functionName) + `Request` : "client: MisskeyClient";
  let match = endpoint.summary;
  let match$1 = endpoint.description;
  let docLines;
  if (match !== undefined) {
    if (match$1 !== undefined) {
      if (match === match$1) {
        docLines = `  /** ` + match + ` */`;
      } else {
        let descLines = match$1.split("\n").map(line => {
          if (line === "") {
            return "   *";
          } else {
            return `   * ` + line;
          }
        });
        docLines = `  /**\n   * ` + match + `\n   *\n` + descLines.join("\n") + `\n   */`;
      }
    } else {
      docLines = `  /** ` + match + ` */`;
    }
  } else if (match$1 !== undefined) {
    let lines = match$1.split("\n").map(line => {
      if (line === "") {
        return "   *";
      } else {
        return `   * ` + line;
      }
    });
    docLines = `  /**\n` + lines.join("\n") + `\n   */`;
  } else {
    docLines = "";
  }
  return Handlebars.render(Templates.methodSignature, {
    docLines: docLines,
    functionName: functionName,
    params: params,
    responsePascalName: JsConvertCase.toPascalCase(functionName)
  });
}

function generateModuleDts(moduleName, endpoints) {
  let interfaces = endpoints.map(endpoint => {
    let functionName = CodegenUtils.generateOperationName(endpoint.operationId, endpoint.path, endpoint.method);
    let requestPart = Stdlib_Option.getOr(generateRequestInterface(endpoint, functionName), "");
    let responsePart = generateResponseInterface(endpoint, functionName);
    return [
      requestPart,
      responsePart
    ].filter(s => s !== "").join("\n");
  }).join("\n\n");
  let methodSignatures = endpoints.map(endpoint => generateMethodSignature(endpoint, CodegenUtils.generateOperationName(endpoint.operationId, endpoint.path, endpoint.method))).join("\n");
  return Handlebars.render(Templates.moduleDts, {
    moduleName: moduleName,
    interfaces: interfaces,
    methodSignatures: methodSignatures
  });
}

function generateComponentSchemasDts(schemas) {
  let content = Object.entries(schemas).map(param => {
    let schema = param[1];
    return generateTypeScriptType(param[0], schema.description, schema);
  }).join("\n\n");
  return Handlebars.render(Templates.componentSchemasDts, {
    content: content
  });
}

function generateIndexDts(moduleNames) {
  let modules = moduleNames.map(m => ({
    importLine: `import { ` + m + `Module } from './` + m + `';`,
    exportLine: `export const ` + m + `: ` + m + `Module;`
  }));
  return Handlebars.render(Templates.indexDts, {
    modules: modules
  });
}

function generate(spec, endpoints, outputDir) {
  let endpointsByTag = OpenAPIParser.groupByTag(endpoints);
  let moduleNames = [];
  let files = Stdlib_Array.filterMap(Object.entries(endpointsByTag), param => {
    let tagEndpoints = param[1];
    if (tagEndpoints.length === 0) {
      return;
    }
    let name = JsConvertCase.toPascalCase(param[0]);
    moduleNames.push(name);
    return {
      path: FileSystem.makePath(outputDir, `types/` + name + `.d.ts`),
      content: generateModuleDts(name, tagEndpoints)
    };
  });
  Stdlib_Option.forEach(Stdlib_Option.flatMap(spec.components, c => c.schemas), schemas => {
    files.push({
      path: FileSystem.makePath(outputDir, "types/ComponentSchemas.d.ts"),
      content: generateComponentSchemasDts(schemas)
    });
  });
  files.push({
    path: FileSystem.makePath(outputDir, "types/index.d.ts"),
    content: generateIndexDts(moduleNames)
  });
  return {
    files: files,
    warnings: []
  };
}

export {
  getFirstJsonSchema,
  generateTypeScriptType,
  generateRequestInterface,
  generateResponseInterface,
  generateMethodSignature,
  generateModuleDts,
  generateComponentSchemasDts,
  generateIndexDts,
  generate,
}
/* FileSystem Not a pure module */
