// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Pipeline from "../core/Pipeline.res.mjs";
import * as Templates from "../core/Templates.res.mjs";
import * as FileSystem from "../core/FileSystem.res.mjs";
import * as Handlebars from "../bindings/Handlebars.res.mjs";
import * as CodegenUtils from "../core/CodegenUtils.res.mjs";
import * as OpenAPIParser from "../core/OpenAPIParser.res.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as JsConvertCase from "js-convert-case";

let body = "export class MisskeyClient {\n  constructor(baseUrl, token) {\n    this.baseUrl = baseUrl;\n    this.token = token;\n  }\n\n  async _fetch(url, method, body) {\n    const headers = { 'Content-Type': 'application/json' };\n    if (this.token) {\n      headers['Authorization'] = \x60Bearer \x24{this.token}\x60;\n    }\n    const response = await fetch(this.baseUrl + url, {\n      method,\n      headers,\n      body: body ? JSON.stringify(body) : undefined,\n    });\n    return response.json();\n  }\n}";

function generateWrapperMjs(endpoints, generatedModulePath, modulePrefix) {
  let endpointsByTag = OpenAPIParser.groupByTag(endpoints);
  let tags = Object.keys(endpointsByTag);
  let tagData = tags.map(tag => {
    let moduleName = JsConvertCase.toPascalCase(tag);
    let importAlias = moduleName + `Api`;
    let importLine = `import * as ` + importAlias + ` from '` + generatedModulePath + `/` + modulePrefix + moduleName + `.res.mjs';`;
    let methods = Stdlib_Option.getOr(endpointsByTag[tag], []).map(endpoint => {
      let functionName = CodegenUtils.generateOperationName(endpoint.operationId, endpoint.path, endpoint.method);
      let hasRequestBody = Stdlib_Option.isSome(endpoint.requestBody);
      return Handlebars.render(Templates.wrapperMjsMethod, {
        functionName: functionName,
        moduleName: importAlias,
        requestArg: hasRequestBody ? ", request" : "",
        bodyArg: hasRequestBody ? "body: request, " : ""
      });
    }).join("\n");
    let namespace = Handlebars.render(Templates.wrapperMjsNamespace, {
      moduleName: moduleName,
      methods: methods
    });
    return {
      importLine: importLine,
      namespace: namespace
    };
  });
  return Handlebars.render(Templates.wrapperMjs, {
    tags: tagData,
    clientCode: body
  });
}

function generateWrapperDts(endpoints) {
  let endpointsByTag = OpenAPIParser.groupByTag(endpoints);
  let tags = Object.keys(endpointsByTag);
  let tagData = tags.map(tag => {
    let moduleName = JsConvertCase.toPascalCase(tag);
    let typesToImport = Stdlib_Option.getOr(endpointsByTag[tag], []).flatMap(endpoint => {
      let pascalName = JsConvertCase.toPascalCase(CodegenUtils.generateOperationName(endpoint.operationId, endpoint.path, endpoint.method));
      if (Stdlib_Option.isSome(endpoint.requestBody)) {
        return [
          `  ` + pascalName + `Request,`,
          `  ` + pascalName + `Response,`
        ];
      } else {
        return [`  ` + pascalName + `Response,`];
      }
    }).join("\n");
    let importBlock = `import type {\n` + typesToImport + `\n} from '../types/` + moduleName + `';`;
    let functions = Stdlib_Option.getOr(endpointsByTag[tag], []).map(endpoint => {
      let functionName = CodegenUtils.generateOperationName(endpoint.operationId, endpoint.path, endpoint.method);
      let pascalName = JsConvertCase.toPascalCase(functionName);
      let match = endpoint.summary;
      let match$1 = endpoint.description;
      let docComment;
      if (match !== undefined) {
        if (match$1 !== undefined) {
          if (match === match$1) {
            docComment = `  /** ` + match + ` */\n`;
          } else {
            let descLines = match$1.split("\n").map(line => {
              if (line === "") {
                return "   *";
              } else {
                return `   * ` + line;
              }
            });
            docComment = `  /**\n   * ` + match + `\n   *\n` + descLines.join("\n") + `\n   */\n`;
          }
        } else {
          docComment = `  /** ` + match + ` */\n`;
        }
      } else if (match$1 !== undefined) {
        let lines = match$1.split("\n").map(line => {
          if (line === "") {
            return "   *";
          } else {
            return `   * ` + line;
          }
        });
        docComment = `  /**\n` + lines.join("\n") + `\n   */\n`;
      } else {
        docComment = "";
      }
      let requestParam = Stdlib_Option.isSome(endpoint.requestBody) ? `, request: ` + pascalName + `Request` : "";
      return Handlebars.render(Templates.wrapperDtsFunction, {
        docComment: docComment,
        functionName: functionName,
        requestParam: requestParam,
        pascalName: pascalName
      });
    }).join("\n");
    let namespace = Handlebars.render(Templates.wrapperDtsNamespace, {
      moduleName: moduleName,
      functions: functions
    });
    return {
      importBlock: importBlock,
      namespace: namespace
    };
  });
  return Handlebars.render(Templates.wrapperDts, {
    tags: tagData
  });
}

function generate(endpoints, outputDir, generatedModulePathOpt, modulePrefixOpt) {
  let generatedModulePath = generatedModulePathOpt !== undefined ? generatedModulePathOpt : "../api";
  let modulePrefix = modulePrefixOpt !== undefined ? modulePrefixOpt : "";
  return Pipeline.fromFilesAndWarnings([
    {
      path: FileSystem.makePath(outputDir, "wrapper/index.mjs"),
      content: generateWrapperMjs(endpoints, generatedModulePath, modulePrefix)
    },
    {
      path: FileSystem.makePath(outputDir, "wrapper/index.d.ts"),
      content: generateWrapperDts(endpoints)
    }
  ], []);
}

let misskeyClientJsCode = body;

export {
  misskeyClientJsCode,
  generateWrapperMjs,
  generateWrapperDts,
  generate,
}
/* FileSystem Not a pure module */
