// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Module from "module";

let _require = Module.createRequire(import.meta.url);

let handlebars = _require("handlebars");

let convert = _require("js-convert-case");

let _render = ((function(Handlebars, convert) {
      var instance = Handlebars.create();

      instance.registerHelper('indent', function(content, level) {
        if (typeof content !== 'string') return '';
        var spaces = '  '.repeat(typeof level === 'number' ? level : 1);
        return content.split('\n').map(function(line) {
          return line.trim() === '' ? '' : spaces + line;
        }).join('\n');
      });
      instance.registerHelper('pascalCase', function(s) { return typeof s === 'string' ? convert.toPascalCase(s) : ''; });
      instance.registerHelper('camelCase', function(s) { return typeof s === 'string' ? convert.toCamelCase(s) : ''; });
      instance.registerHelper('upperCase', function(s) { return typeof s === 'string' ? s.toUpperCase() : ''; });
      instance.registerHelper('eq', function(a, b) { return a === b; });
      instance.registerHelper('ne', function(a, b) { return a !== b; });

      var cache = {};
      return function render(template, data) {
        if (!cache[template]) cache[template] = instance.compile(template, { noEscape: true });
        return cache[template](data);
      };
    }))(handlebars, convert);

function render(template, data) {
  return _render(template, data);
}

export {
  _require,
  _render,
  render,
}
/* _require Not a pure module */
