// Generated by ReScript, PLEASE EDIT WITH CARE

import Toposort from "toposort";

function sortArray(nodes, edges) {
  return Toposort.array(nodes, edges);
}

export {
  sortArray,
}
/* toposort Not a pure module */
