// Generated by ReScript, PLEASE EDIT WITH CARE


function toString(w) {
  switch (w.TAG) {
    case "FallbackToJson" :
      let context = w.context;
      return `⚠️  Falling back to JSON.t at '` + context.path + `' (` + context.operation + `): ` + w.reason;
    case "UnsupportedFeature" :
      return `⚠️  Unsupported feature '` + w.feature + `' at '` + w.location + `', using fallback: ` + w.fallback;
    case "DepthLimitReached" :
      return `⚠️  Depth limit ` + w.depth.toString() + ` reached at '` + w.path + `', using simplified type`;
    case "MissingSchema" :
      return `⚠️  Schema reference '` + w.ref + `' not found at '` + w.location + `'`;
    case "IntersectionNotFullySupported" :
      return `⚠️  Intersection type at '` + w.location + `' not fully supported: ` + w.note;
    case "ComplexUnionSimplified" :
      return `⚠️  Complex union at '` + w.location + `' simplified (types: ` + w.types + `)`;
  }
}

function print(warnings) {
  if (warnings.length !== 0) {
    console.log("\n⚠️  Warnings:");
    warnings.forEach(w => {
      console.log(toString(w));
    });
    return;
  }
}

let Warning = {
  toString: toString,
  print: print
};

function toString$1(e) {
  switch (e.TAG) {
    case "SpecResolutionError" :
      return `Failed to resolve spec from '` + e.url + `': ` + e.message;
    case "SchemaParseError" :
      let context = e.context;
      return `Failed to parse schema at '` + context.path + `' (` + context.operation + `): ` + e.reason;
    case "ReferenceError" :
      let context$1 = e.context;
      return `Failed to resolve reference '` + e.ref + `' at '` + context$1.path + `' (` + context$1.operation + `)`;
    case "ValidationError" :
      return `Validation failed for schema '` + e.schema + `': ` + e.issues.join(", ");
    case "CircularSchemaError" :
      return `Circular schema detected for '` + e.ref + `' at depth ` + e.depth.toString() + ` (path: ` + e.path + `)`;
    case "FileWriteError" :
      return `Failed to write file '` + e.filePath + `': ` + e.message;
    case "InvalidConfigError" :
      return `Invalid configuration for field '` + e.field + `': ` + e.message;
    case "UnknownError" :
      let context$2 = e.context;
      let message = e.message;
      if (context$2 !== undefined) {
        return `Unknown error at '` + context$2.path + `' (` + context$2.operation + `): ` + message;
      } else {
        return `Unknown error: ` + message;
      }
  }
}

function makeContext(path, operation, schema, param) {
  return {
    path: path,
    operation: operation,
    schema: schema
  };
}

export {
  Warning,
  toString$1 as toString,
  makeContext,
}
/* No side effect */
