// Generated by ReScript, PLEASE EDIT WITH CARE


function make(specPath, outputDir, strategyOpt, modulePerTagOpt, includeTags, excludeTags, generateDiffReportOpt, breakingChangeHandlingOpt, forkSpecs, generateDocOverrides, docOverrideDir, targets, dtsOutputDir, wrapperOutputDir, baseInstanceName, baseModulePrefix, param) {
  let strategy = strategyOpt !== undefined ? strategyOpt : "SharedBase";
  let modulePerTag = modulePerTagOpt !== undefined ? modulePerTagOpt : true;
  let generateDiffReport = generateDiffReportOpt !== undefined ? generateDiffReportOpt : true;
  let breakingChangeHandling = breakingChangeHandlingOpt !== undefined ? breakingChangeHandlingOpt : "Warn";
  return {
    specPath: specPath,
    forkSpecs: forkSpecs,
    outputDir: outputDir,
    strategy: strategy,
    modulePerTag: modulePerTag,
    includeTags: includeTags,
    excludeTags: excludeTags,
    generateDiffReport: generateDiffReport,
    breakingChangeHandling: breakingChangeHandling,
    generateDocOverrides: generateDocOverrides,
    docOverrideDir: docOverrideDir,
    targets: targets,
    dtsOutputDir: dtsOutputDir,
    wrapperOutputDir: wrapperOutputDir,
    baseInstanceName: baseInstanceName,
    baseModulePrefix: baseModulePrefix
  };
}

function defaultTargets() {
  return {
    rescriptApi: true,
    rescriptWrapper: false,
    typescriptDts: false,
    typescriptWrapper: false
  };
}

export {
  make,
  defaultTargets,
}
/* No side effect */
