// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SchemaIR from "../core/SchemaIR.res.mjs";

function make(path, insideComponentSchemasOpt, availableSchemas, modulePrefixOpt, selfRefName, param) {
  let insideComponentSchemas = insideComponentSchemasOpt !== undefined ? insideComponentSchemasOpt : false;
  let modulePrefix = modulePrefixOpt !== undefined ? modulePrefixOpt : "";
  return {
    warnings: [],
    extractedTypes: [],
    extractCounter: 0,
    path: path,
    insideComponentSchemas: insideComponentSchemas,
    availableSchemas: availableSchemas,
    modulePrefix: modulePrefix,
    selfRefName: selfRefName
  };
}

function addWarning(ctx, warning) {
  ctx.warnings.push(warning);
}

function extractType(ctx, baseName, isUnboxedOpt, irType) {
  let isUnboxed = isUnboxedOpt !== undefined ? isUnboxedOpt : false;
  let existing = ctx.extractedTypes.find(param => SchemaIR.equals(param.irType, irType));
  if (existing !== undefined) {
    return existing.typeName;
  }
  ctx.extractCounter = ctx.extractCounter + 1 | 0;
  let first = baseName.charAt(0);
  let lowerBaseName = first === "" ? "extracted" : first.toLowerCase() + baseName.slice(1);
  let typeName = lowerBaseName + `_` + ctx.extractCounter.toString();
  ctx.extractedTypes.push({
    typeName: typeName,
    irType: irType,
    isUnboxed: isUnboxed
  });
  return typeName;
}

export {
  make,
  addWarning,
  extractType,
}
/* No side effect */
