// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Templates from "./Templates.res.mjs";
import * as Handlebars from "../bindings/Handlebars.res.mjs";
import * as Stdlib_Null from "@rescript/runtime/lib/es6/Stdlib_Null.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as JsConvertCase from "js-convert-case";

function sanitizeIdentifier(str) {
  return str.replaceAll("{", "").replaceAll("}", "").replaceAll("[", "").replaceAll("]", "").replaceAll(".", "_").replaceAll("-", "_").replaceAll("/", "_").replaceAll(" ", "_");
}

function generateTypeName(prefixOpt, path, suffix) {
  let prefix = prefixOpt !== undefined ? prefixOpt : "";
  let cleaned = sanitizeIdentifier(path.replaceAll("/", "_")).split("_").filter(part => part !== "").map(prim => JsConvertCase.toPascalCase(prim)).join("");
  return prefix + cleaned + suffix;
}

function generateOperationName(operationId, path, method) {
  if (operationId !== undefined) {
    return JsConvertCase.toCamelCase(sanitizeIdentifier(operationId));
  } else {
    return method.toLowerCase() + path.split("/").filter(part => {
      if (part !== "") {
        return !part.startsWith("{");
      } else {
        return false;
      }
    }).map(prim => JsConvertCase.toCamelCase(prim)).join("");
  }
}

function escapeString(str) {
  return str.replaceAll("\\", "\\\\").replaceAll("\"", "\\\"").replaceAll("\n", "\\n").replaceAll("\r", "\\r").replaceAll("\t", "\\t");
}

function escapeRegexPattern(str) {
  return (function(s) {
      return s.replace(/\[([^\]]+)\]/g, function(match) {
        let content = match.slice(1, -1);
        let chars = [];
        let hyphenCount = 0;
        let i = 0;
        
        while (i < content.length) {
          if (content[i] === '\\\\' && i + 1 < content.length) {
            if (content[i + 1] === '-') {
              // Escaped hyphen - count it and skip
              hyphenCount++;
              i += 2;
            } else {
              // Other escaped char - keep as is
              chars.push(content[i]);
              chars.push(content[i + 1]);
              i += 2;
            }
          } else if (content[i] === '-' && i > 0 && i < content.length - 1) {
            // Check if this hyphen is part of a valid range
            let prevChar = chars[chars.length - 1];
            let nextChar = content[i + 1];
            // If previous char is a backslash, this can't be a range
            if (chars.length >= 2 && chars[chars.length - 2] === '\\\\') {
              // Previous was escaped, so this hyphen is literal
              hyphenCount++;
              i++;
            } else if (nextChar === '\\\\') {
              // Next is escape sequence, hyphen is literal
              hyphenCount++;
              i++;
            } else if (prevChar && nextChar && prevChar.charCodeAt(0) < nextChar.charCodeAt(0)) {
              // Valid range (e.g., a-z), keep the hyphen
              chars.push('-');
              i++;
            } else {
              // Invalid or ambiguous, move to end
              hyphenCount++;
              i++;
            }
          } else {
            // Regular character or hyphen at start/end
            chars.push(content[i]);
            i++;
          }
        }
        
        // Add collected hyphens at the end
        let result = chars.join('');
        if (hyphenCount > 0) {
          result += '-'.repeat(hyphenCount);
        }
        return '[' + result + ']';
      });
    })(str);
}

function generateFileHeader(description) {
  return Handlebars.render(Templates.fileHeader, {
    description: description
  });
}

function indent(code, level) {
  let spaces = "  ".repeat(level);
  return code.split("\n").map(line => {
    if (line.trim() === "") {
      return "";
    } else {
      return spaces + line;
    }
  }).join("\n");
}

let rescriptKeywords = [
  "and",
  "as",
  "assert",
  "async",
  "await",
  "catch",
  "class",
  "constraint",
  "do",
  "done",
  "downto",
  "else",
  "end",
  "exception",
  "external",
  "false",
  "for",
  "fun",
  "function",
  "functor",
  "if",
  "in",
  "include",
  "inherit",
  "initializer",
  "lazy",
  "let",
  "method",
  "module",
  "mutable",
  "new",
  "nonrec",
  "object",
  "of",
  "open",
  "or",
  "private",
  "rec",
  "sig",
  "struct",
  "switch",
  "then",
  "to",
  "true",
  "try",
  "type",
  "val",
  "virtual",
  "when",
  "while",
  "with"
];

function escapeKeyword(name) {
  if (rescriptKeywords.includes(name)) {
    return name + "_";
  } else {
    return name;
  }
}

function generateDocComment(summary, description, param) {
  return Handlebars.render(Templates.docComment, {
    summary: Stdlib_Null.fromOption(summary),
    description: Stdlib_Null.fromOption(description)
  });
}

function generateDocString(summary, description, param) {
  let content = summary !== undefined ? (
      description !== undefined ? (
          summary === description ? summary : summary + "\n\n" + description
        ) : summary
    ) : (
      description !== undefined ? description : undefined
    );
  return Stdlib_Option.getOr(Stdlib_Option.map(content, text => {
    let lines = text.trim().split("\n").map(prim => prim.trim());
    let len = lines.length;
    if (len !== 1) {
      if (len !== 0) {
        return Handlebars.render(Templates.docCommentMulti, {
          lines: lines
        });
      } else {
        return "";
      }
    }
    let line = lines[0];
    return Handlebars.render(Templates.docCommentSingle, {
      content: line
    });
  }), "");
}

function variantConstructorName(_irType) {
  while (true) {
    let irType = _irType;
    if (typeof irType !== "object") {
      switch (irType) {
        case "Boolean" :
          return "Bool";
        case "Null" :
          return "Null";
        case "Unknown" :
          return "Unknown";
      }
    } else {
      switch (irType.TAG) {
        case "String" :
          return "String";
        case "Number" :
          return "Float";
        case "Integer" :
          return "Int";
        case "Array" :
          return "Array";
        case "Object" :
          return "Object";
        case "Literal" :
          let s = irType._0;
          if (typeof s !== "object") {
            return "Null";
          }
          switch (s.TAG) {
            case "StringLiteral" :
              return JsConvertCase.toPascalCase(s._0);
            case "NumberLiteral" :
              return "Number";
            case "BooleanLiteral" :
              return "Bool";
          }
        case "Union" :
          return "Union";
        case "Intersection" :
          return "Intersection";
        case "Reference" :
          let ref = irType._0;
          return JsConvertCase.toPascalCase(ref.includes("/") ? Stdlib_Option.getOr(ref.split("/")[ref.split("/").length - 1 | 0], "Ref") : ref);
        case "Option" :
          _irType = irType._0;
          continue;
      }
    }
  };
}

function deduplicateNames(names) {
  let counts = {};
  let result = [];
  names.forEach(name => {
    let count = Stdlib_Option.getOr(counts[name], 0);
    counts[name] = count + 1 | 0;
  });
  let seen = {};
  names.forEach(name => {
    let total = Stdlib_Option.getOr(counts[name], 1);
    if (total > 1) {
      let idx = Stdlib_Option.getOr(seen[name], 0) + 1 | 0;
      seen[name] = idx;
      result.push(name + idx.toString());
      return;
    }
    result.push(name);
  });
  return result;
}

let fetchTypeSignature = "(~url: string, ~method_: string, ~body: option<JSON.t>) => Promise.t<JSON.t>";

export {
  sanitizeIdentifier,
  generateTypeName,
  generateOperationName,
  escapeString,
  escapeRegexPattern,
  generateFileHeader,
  indent,
  rescriptKeywords,
  escapeKeyword,
  generateDocComment,
  generateDocString,
  fetchTypeSignature,
  variantConstructorName,
  deduplicateNames,
}
/* Handlebars Not a pure module */
