// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fs from "fs";
import * as Js_string from "@rescript/runtime/lib/es6/Js_string.js";
import * as Templates from "./Templates.res.mjs";
import * as FileSystem from "./FileSystem.res.mjs";
import * as Handlebars from "../bindings/Handlebars.res.mjs";
import * as CodegenUtils from "./CodegenUtils.res.mjs";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Stdlib_JsExn from "@rescript/runtime/lib/es6/Stdlib_JsExn.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as JsConvertCase from "js-convert-case";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

function generateEndpointHash(endpoint) {
  let parts = [
    endpoint.path,
    endpoint.method,
    Stdlib_Option.getOr(endpoint.operationId, ""),
    Stdlib_Option.getOr(endpoint.summary, ""),
    Stdlib_Option.getOr(endpoint.description, "")
  ];
  let combined = parts.join("|");
  return Stdlib_Array.reduce(combined.split(""), 0, (acc, char) => {
    let code = Js_string.charCodeAt(0, char) | 0;
    return (((acc << 5) - acc | 0) + code | 0) % 2147483647;
  }).toString(16);
}

function extractCodeBlock(markdown) {
  let parts = markdown.split("```");
  if (parts.length < 3) {
    return;
  }
  let content = parts[1];
  if (content === undefined) {
    return;
  }
  let trimmed = content.trim();
  if (trimmed === "" || trimmed === "<!-- Empty - no override -->") {
    return;
  } else {
    return trimmed;
  }
}

function parseOverrideMarkdown(content) {
  let parts = content.split("---");
  if (parts.length < 3) {
    return;
  }
  let frontmatter = Stdlib_Option.getOr(parts[1], "");
  let body = parts.slice(2, parts.length).join("---").trim();
  let lines = frontmatter.split("\n").map(prim => prim.trim());
  let metadata_endpoint = Stdlib_Option.getOr(Stdlib_Option.map(lines.find(l => l.startsWith("endpoint:")), l => {
    let parts = l.split(":");
    return parts.slice(1, parts.length).join(":").trim();
  }), "");
  let metadata_method = Stdlib_Option.getOr(Stdlib_Option.map(lines.find(l => l.startsWith("method:")), l => Stdlib_Option.getOr(l.split(":")[1], "").trim()), "");
  let metadata_hash = Stdlib_Option.getOr(Stdlib_Option.map(lines.find(l => l.startsWith("hash:")), l => Stdlib_Option.getOr(l.split(":")[1], "").trim()), "");
  let metadata_host = Stdlib_Option.flatMap(lines.find(l => l.startsWith("host:")), l => {
    let parts = l.split(":");
    return parts.slice(1, parts.length).join(":").trim();
  });
  let metadata_version = Stdlib_Option.flatMap(lines.find(l => l.startsWith("version:")), l => Stdlib_Option.map(l.split(":")[1], prim => prim.trim()));
  let metadata_operationId = Stdlib_Option.flatMap(lines.find(l => l.startsWith("operationId:")), l => Stdlib_Option.map(l.split(":")[1], prim => prim.trim()));
  let metadata = {
    endpoint: metadata_endpoint,
    method: metadata_method,
    hash: metadata_hash,
    host: metadata_host,
    version: metadata_version,
    operationId: metadata_operationId
  };
  let parts$1 = Stdlib_Option.getOr(body.split("## Override")[0], "").split("## Default Description");
  let defaultDescSection = parts$1.slice(1, parts$1.length).join("## Default Description").trim();
  let parts$2 = body.split("## Override");
  let overrideSection = parts$2.slice(1, parts$2.length).join("## Override");
  let overrideDesc = extractCodeBlock(overrideSection);
  let hasOverride = Stdlib_Option.isSome(overrideDesc);
  return {
    metadata: metadata,
    defaultDescription: defaultDescSection,
    overrideDescription: overrideDesc,
    hasOverride: hasOverride
  };
}

function generateOverrideMarkdown(endpoint, host, version, param) {
  let hash = generateEndpointHash(endpoint);
  let operationName = CodegenUtils.generateOperationName(endpoint.operationId, endpoint.path, endpoint.method);
  let match = endpoint.summary;
  let match$1 = endpoint.description;
  let defaultDesc = match !== undefined ? (
      match$1 !== undefined && match !== match$1 ? match + "\n\n" + match$1 : match
    ) : (
      match$1 !== undefined ? match$1 : "No description provided."
    );
  let metadata = [
    "---",
    `endpoint: ` + endpoint.path,
    `method: ` + endpoint.method.toUpperCase(),
    `hash: ` + hash
  ].concat(Stdlib_Array.filterMap([
    Stdlib_Option.map(host, h => `host: ` + h),
    Stdlib_Option.map(version, v => `version: ` + v),
    Stdlib_Option.map(endpoint.operationId, id => `operationId: ` + id),
    "---"
  ], x => x));
  return Handlebars.render(Templates.overrideMarkdown, {
    metadataBlock: metadata.join("\n"),
    title: Stdlib_Option.getOr(endpoint.summary, endpoint.path),
    path: endpoint.path,
    methodUpper: endpoint.method.toUpperCase(),
    operationName: operationName,
    defaultDesc: defaultDesc
  });
}

function validateOverride(override, currentHash) {
  if (override.metadata.hash === currentHash) {
    return "Valid";
  } else {
    return {
      TAG: "HashMismatch",
      expected: currentHash,
      found: override.metadata.hash
    };
  }
}

function readOverrideWithValidation(overrideDir, moduleName, functionName, currentHash) {
  let filePath = FileSystem.makePath(FileSystem.makePath(overrideDir, moduleName), functionName + ".md");
  if (!Fs.existsSync(filePath)) {
    return "NoOverride";
  }
  try {
    let content = Fs.readFileSync(filePath, {
      encoding: "utf8"
    });
    let parsed = parseOverrideMarkdown(content);
    if (parsed === undefined) {
      return {
        TAG: "FileError",
        _0: "Failed to parse markdown file"
      };
    }
    if (!parsed.hasOverride) {
      return "NoOverride";
    }
    let msg = validateOverride(parsed, currentHash);
    if (typeof msg !== "object") {
      if (msg !== "Valid") {
        return {
          TAG: "FileError",
          _0: "Override file missing"
        };
      }
      let desc = parsed.overrideDescription;
      if (desc !== undefined) {
        return {
          TAG: "ValidOverride",
          _0: desc
        };
      } else {
        return "NoOverride";
      }
    } else {
      if (msg.TAG !== "HashMismatch") {
        return {
          TAG: "FileError",
          _0: msg._0
        };
      }
      let desc$1 = parsed.overrideDescription;
      if (desc$1 !== undefined) {
        return {
          TAG: "InvalidHash",
          override: desc$1,
          expected: msg.expected,
          found: msg.found
        };
      } else {
        return "NoOverride";
      }
    }
  } catch (raw_err) {
    let err = Primitive_exceptions.internalToException(raw_err);
    if (err.RE_EXN_ID === "JsExn") {
      return {
        TAG: "FileError",
        _0: Stdlib_Option.getOr(Stdlib_JsExn.message(err._1), "Unknown error")
      };
    } else {
      return {
        TAG: "FileError",
        _0: "Unknown error reading file"
      };
    }
  }
}

function readOverride(overrideDir, moduleName, functionName) {
  let filePath = FileSystem.makePath(FileSystem.makePath(overrideDir, moduleName), functionName + ".md");
  if (!Fs.existsSync(filePath)) {
    return;
  }
  try {
    let content = Fs.readFileSync(filePath, {
      encoding: "utf8"
    });
    let parsed = parseOverrideMarkdown(content);
    if (parsed !== undefined) {
      return parsed.overrideDescription;
    } else {
      return;
    }
  } catch (exn) {
    return;
  }
}

function isFileCustomized(filePath) {
  if (!Fs.existsSync(filePath)) {
    return false;
  }
  try {
    let content = Fs.readFileSync(filePath, {
      encoding: "utf8"
    });
    let parsed = parseOverrideMarkdown(content);
    if (parsed !== undefined) {
      return parsed.hasOverride;
    } else {
      return false;
    }
  } catch (exn) {
    return false;
  }
}

function generateOverrideFiles(spec, endpoints, outputDir, host, groupByTagOpt, param) {
  let groupByTag = groupByTagOpt !== undefined ? groupByTagOpt : true;
  let version = spec.info.version;
  let hostUrl = host !== undefined ? host : spec.info.description;
  return Stdlib_Array.keepSome(endpoints.map(endpoint => {
    let moduleName;
    if (groupByTag) {
      let tags = endpoint.tags;
      moduleName = tags !== undefined ? Stdlib_Option.getOr(tags[0], "Default") : "Default";
    } else {
      moduleName = "API";
    }
    let functionName = CodegenUtils.generateOperationName(endpoint.operationId, endpoint.path, endpoint.method);
    let modulePath = FileSystem.makePath(outputDir, JsConvertCase.toPascalCase(moduleName));
    let filePath = FileSystem.makePath(modulePath, functionName + ".md");
    if (isFileCustomized(filePath)) {
      console.log(`ℹ️  Skipping ` + moduleName + `/` + functionName + ` - file already customized`);
      return;
    }
    let content = generateOverrideMarkdown(endpoint, hostUrl, version, undefined);
    return {
      path: filePath,
      content: content
    };
  }));
}

function generateOverrideReadme(host, version, param) {
  let hostInfo = Stdlib_Option.getOr(host, "Not specified");
  let versionInfo = Stdlib_Option.getOr(version, "Not specified");
  return Handlebars.render(Templates.overrideReadme, {
    hostInfo: hostInfo,
    versionInfo: versionInfo
  });
}

export {
  generateEndpointHash,
  extractCodeBlock,
  parseOverrideMarkdown,
  generateOverrideMarkdown,
  validateOverride,
  readOverrideWithValidation,
  readOverride,
  isFileCustomized,
  generateOverrideFiles,
  generateOverrideReadme,
}
/* fs Not a pure module */
