// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fs from "fs";
import * as Pathe from "pathe";
import * as Stdlib_JsExn from "@rescript/runtime/lib/es6/Stdlib_JsExn.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

function ensureDir(path) {
  try {
    Fs.mkdirSync(Pathe.dirname(path), {
      recursive: true
    });
    return;
  } catch (exn) {
    return;
  }
}

function writeFile(file) {
  try {
    ensureDir(file.path);
    Fs.writeFileSync(file.path, file.content, "utf8");
    return {
      TAG: "Ok",
      _0: undefined
    };
  } catch (raw_exn) {
    let exn = Primitive_exceptions.internalToException(raw_exn);
    if (exn.RE_EXN_ID !== "JsExn") {
      return {
        TAG: "Error",
        _0: `Failed to write file ` + file.path + `: Unknown error`
      };
    }
    let message = Stdlib_Option.getOr(Stdlib_JsExn.message(exn._1), "Unknown error");
    return {
      TAG: "Error",
      _0: `Failed to write file ` + file.path + `: ` + message
    };
  }
}

function writeFiles(files) {
  let successes = [];
  let errors = [];
  files.forEach(file => {
    let err = writeFile(file);
    if (err.TAG === "Ok") {
      successes.push(file.path);
      return;
    }
    errors.push(err._0);
  });
  if (errors.length !== 0) {
    return {
      TAG: "Error",
      _0: errors
    };
  } else {
    return {
      TAG: "Ok",
      _0: successes
    };
  }
}

function makePath(baseDir, filename) {
  return Pathe.join(baseDir, filename);
}

export {
  ensureDir,
  writeFile,
  writeFiles,
  makePath,
}
/* fs Not a pure module */
