// Generated by ReScript, PLEASE EDIT WITH CARE


function string(min, max, pattern, param) {
  return {
    minLength: min,
    maxLength: max,
    pattern: pattern
  };
}

function number(min, max, multipleOf, param) {
  return {
    minimum: min,
    maximum: max,
    multipleOf: multipleOf
  };
}

function array(min, max, uniqueOpt, param) {
  let unique = uniqueOpt !== undefined ? uniqueOpt : false;
  return {
    minItems: min,
    maxItems: max,
    uniqueItems: unique
  };
}

let Constraints = {
  string: string,
  number: number,
  array: array
};

function string$1(min, max, pattern, param) {
  return {
    TAG: "String",
    constraints: {
      minLength: min,
      maxLength: max,
      pattern: pattern
    }
  };
}

function number$1(min, max, multipleOf, param) {
  return {
    TAG: "Number",
    constraints: {
      minimum: min,
      maximum: max,
      multipleOf: multipleOf
    }
  };
}

function int(min, max, multipleOf, param) {
  return {
    TAG: "Integer",
    constraints: {
      minimum: min,
      maximum: max,
      multipleOf: multipleOf
    }
  };
}

function array$1(items, min, max, uniqueOpt, param) {
  let unique = uniqueOpt !== undefined ? uniqueOpt : false;
  return {
    TAG: "Array",
    items: items,
    constraints: array(min, max, unique, undefined)
  };
}

function object_(props, additional, param) {
  return {
    TAG: "Object",
    properties: props,
    additionalProperties: additional
  };
}

function union(types) {
  return {
    TAG: "Union",
    _0: types
  };
}

function intersection(types) {
  return {
    TAG: "Intersection",
    _0: types
  };
}

function ref(refPath) {
  return {
    TAG: "Reference",
    _0: refPath
  };
}

function option(type_) {
  return {
    TAG: "Option",
    _0: type_
  };
}

function stringLit(s) {
  return {
    TAG: "Literal",
    _0: {
      TAG: "StringLiteral",
      _0: s
    }
  };
}

function numberLit(n) {
  return {
    TAG: "Literal",
    _0: {
      TAG: "NumberLiteral",
      _0: n
    }
  };
}

function boolLit(b) {
  return {
    TAG: "Literal",
    _0: {
      TAG: "BooleanLiteral",
      _0: b
    }
  };
}

function prop(name, type_, requiredOpt, param) {
  let required = requiredOpt !== undefined ? requiredOpt : true;
  return [
    name,
    type_,
    required
  ];
}

function optProp(name, type_) {
  return [
    name,
    type_,
    false
  ];
}

function named(name, description, type_) {
  return {
    name: name,
    description: description,
    type_: type_
  };
}

let bool = "Boolean";

let $$null = "Null";

let unknown = "Unknown";

let nullLit = {
  TAG: "Literal",
  _0: "NullLiteral"
};

export {
  Constraints,
  string$1 as string,
  number$1 as number,
  int,
  bool,
  $$null,
  unknown,
  array$1 as array,
  object_,
  union,
  intersection,
  ref,
  option,
  stringLit,
  numberLit,
  boolLit,
  nullLit,
  prop,
  optProp,
  named,
}
/* No side effect */
