// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

function parseMethod(methodStr) {
  let match = methodStr.toLowerCase();
  switch (match) {
    case "delete" :
      return "DELETE";
    case "get" :
      return "GET";
    case "head" :
      return "HEAD";
    case "options" :
      return "OPTIONS";
    case "patch" :
      return "PATCH";
    case "post" :
      return "POST";
    case "put" :
      return "PUT";
    default:
      return;
  }
}

function httpMethodToString(method) {
  if (method === "GET") {
    return "get";
  } else if (method === "PUT") {
    return "put";
  } else if (method === "DELETE") {
    return "delete";
  } else if (method === "HEAD") {
    return "head";
  } else if (method === "POST") {
    return "post";
  } else if (method === "PATCH") {
    return "patch";
  } else {
    return "options";
  }
}

function tupleToEndpoint(param) {
  let operation = param[2];
  return {
    path: param[0],
    method: httpMethodToString(param[1]),
    operationId: operation.operationId,
    summary: operation.summary,
    description: operation.description,
    tags: operation.tags,
    requestBody: operation.requestBody,
    responses: operation.responses,
    parameters: operation.parameters
  };
}

function getOperations(path, param) {
  return Stdlib_Array.filterMap([
    [
      "GET",
      param.get
    ],
    [
      "POST",
      param.post
    ],
    [
      "PUT",
      param.put
    ],
    [
      "PATCH",
      param.patch
    ],
    [
      "DELETE",
      param.delete
    ],
    [
      "HEAD",
      param.head
    ],
    [
      "OPTIONS",
      param.options
    ]
  ], param => {
    let method = param[0];
    return Stdlib_Option.map(param[1], op => [
      path,
      method,
      op
    ]);
  });
}

function getAllEndpoints(spec) {
  let pathsArray = Object.entries(spec.paths);
  return pathsArray.flatMap(param => getOperations(param[0], param[1])).map(tupleToEndpoint);
}

function groupByTag(endpoints) {
  let grouped = {};
  endpoints.forEach(endpoint => {
    let tags = Stdlib_Option.getOr(endpoint.tags, ["default"]);
    tags.forEach(tag => {
      let existing = Stdlib_Option.getOr(grouped[tag], []);
      existing.push(endpoint);
      grouped[tag] = existing;
    });
  });
  return grouped;
}

function getAllSchemas(spec) {
  return Stdlib_Option.getOr(Stdlib_Option.flatMap(spec.components, c => c.schemas), {});
}

function getOperationId(path, method, operation) {
  let methodStr = method === "GET" ? "get" : (
      method === "PUT" ? "put" : (
          method === "DELETE" ? "delete" : (
              method === "HEAD" ? "head" : (
                  method === "POST" ? "post" : (
                      method === "PATCH" ? "patch" : "options"
                    )
                )
            )
        )
    );
  let pathParts = path.replaceAll("/", "_").replaceAll("{", "").replaceAll("}", "").replaceAll("-", "_");
  return Stdlib_Option.getOr(operation.operationId, methodStr + pathParts);
}

function filterByTags(endpoints, includeTags, excludeTags) {
  return endpoints.filter(endpoint => {
    let operationTags = Stdlib_Option.getOr(endpoint.tags, []);
    let included = operationTags.some(tag => includeTags.includes(tag));
    let excluded = operationTags.some(tag => excludeTags.includes(tag));
    if (included) {
      return !excluded;
    } else {
      return false;
    }
  });
}

function getAllTags(endpoints) {
  return Array.from(new Set(endpoints.flatMap(endpoint => Stdlib_Option.getOr(endpoint.tags, []))));
}

export {
  parseMethod,
  httpMethodToString,
  tupleToEndpoint,
  getOperations,
  getAllEndpoints,
  groupByTag,
  getAllSchemas,
  getOperationId,
  filterByTags,
  getAllTags,
}
/* No side effect */
