// Generated by ReScript, PLEASE EDIT WITH CARE


let empty_files = [];

let empty_warnings = [];

let empty = {
  files: empty_files,
  warnings: empty_warnings
};

function merge(a, b) {
  return {
    files: a.files.concat(b.files),
    warnings: a.warnings.concat(b.warnings)
  };
}

function combine(outputs) {
  return {
    files: outputs.flatMap(p => p.files),
    warnings: outputs.flatMap(p => p.warnings)
  };
}

function addFile(file, p) {
  return {
    files: p.files.concat([file]),
    warnings: p.warnings
  };
}

function addFiles(files, p) {
  return {
    files: p.files.concat(files),
    warnings: p.warnings
  };
}

function addWarning(warning, p) {
  return {
    files: p.files,
    warnings: p.warnings.concat([warning])
  };
}

function addWarnings(warnings, p) {
  return {
    files: p.files,
    warnings: p.warnings.concat(warnings)
  };
}

function mapFiles(fn, p) {
  return {
    files: p.files.map(fn),
    warnings: p.warnings
  };
}

function filterWarnings(pred, p) {
  return {
    files: p.files,
    warnings: p.warnings.filter(pred)
  };
}

function make(filesOpt, warningsOpt, param) {
  let files = filesOpt !== undefined ? filesOpt : [];
  let warnings = warningsOpt !== undefined ? warningsOpt : [];
  return {
    files: files,
    warnings: warnings
  };
}

function fromFile(file) {
  return make([file], undefined, undefined);
}

function fromFiles(files) {
  return make(files, undefined, undefined);
}

function fromWarning(warning) {
  return make(undefined, [warning], undefined);
}

function fromWarnings(warnings) {
  return make(undefined, warnings, undefined);
}

function files(p) {
  return p.files;
}

function warnings(p) {
  return p.warnings;
}

function fileCount(p) {
  return p.files.length;
}

function warningCount(p) {
  return p.warnings.length;
}

function filePaths(p) {
  return p.files.map(f => f.path);
}

function withWarnings(p, w) {
  return addWarnings(w, p);
}

function withFiles(p, f) {
  return addFiles(f, p);
}

function fromFilesAndWarnings(files, warnings) {
  return make(files, warnings, undefined);
}

export {
  empty,
  merge,
  combine,
  addFile,
  addFiles,
  addWarning,
  addWarnings,
  mapFiles,
  filterWarnings,
  make,
  fromFile,
  fromFiles,
  fromWarning,
  fromWarnings,
  files,
  warnings,
  fileCount,
  warningCount,
  filePaths,
  withWarnings,
  withFiles,
  fromFilesAndWarnings,
}
/* No side effect */
