// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsConvertCase from "js-convert-case";

function refToTypePath(insideComponentSchemasOpt, modulePrefixOpt, ref) {
  let insideComponentSchemas = insideComponentSchemasOpt !== undefined ? insideComponentSchemasOpt : false;
  let modulePrefix = modulePrefixOpt !== undefined ? modulePrefixOpt : "";
  let parts = ref.split("/");
  let schemaName = parts[parts.length - 1 | 0];
  if (schemaName === undefined) {
    return;
  }
  let moduleName = JsConvertCase.toPascalCase(schemaName);
  if (insideComponentSchemas) {
    return moduleName + `.t`;
  } else {
    return modulePrefix + `ComponentSchemas.` + moduleName + `.t`;
  }
}

function refToSchemaPath(insideComponentSchemasOpt, modulePrefixOpt, ref) {
  let insideComponentSchemas = insideComponentSchemasOpt !== undefined ? insideComponentSchemasOpt : false;
  let modulePrefix = modulePrefixOpt !== undefined ? modulePrefixOpt : "";
  let parts = ref.split("/");
  let schemaName = parts[parts.length - 1 | 0];
  if (schemaName === undefined) {
    return;
  }
  let moduleName = JsConvertCase.toPascalCase(schemaName);
  if (insideComponentSchemas) {
    return moduleName + `.schema`;
  } else {
    return modulePrefix + `ComponentSchemas.` + moduleName + `.schema`;
  }
}

export {
  refToTypePath,
  refToSchemaPath,
}
/* js-convert-case Not a pure module */
