// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

function fromSpec(spec) {
  let components = spec.components;
  let schemas;
  if (components !== undefined) {
    let s = components.schemas;
    schemas = s !== undefined ? s : ({});
  } else {
    schemas = {};
  }
  return {
    schemas: schemas,
    visiting: []
  };
}

function empty() {
  return {
    schemas: {},
    visiting: []
  };
}

function extractSchemaName(ref) {
  let prefix = "#/components/schemas/";
  if (ref.startsWith(prefix)) {
    return ref.slice(prefix.length);
  }
}

function isVisiting(registry, name) {
  return registry.visiting.includes(name);
}

function startVisiting(registry, name) {
  registry.visiting = registry.visiting.concat([name]);
}

function stopVisiting(registry, name) {
  registry.visiting = registry.visiting.filter(n => n !== name);
}

function getSchema(registry, name) {
  return registry.schemas[name];
}

function resolveRef(registry, ref) {
  let name = extractSchemaName(ref);
  if (name !== undefined) {
    return registry.schemas[name];
  }
}

function getSchemaNames(registry) {
  return Object.keys(registry.schemas);
}

function hasSchema(registry, name) {
  return Stdlib_Option.isSome(registry.schemas[name]);
}

function addSchema(registry, name, schema) {
  registry.schemas[name] = schema;
}

function merge(registry, other) {
  Object.entries(other.schemas).forEach(param => {
    let name = param[0];
    if (!hasSchema(registry, name)) {
      return addSchema(registry, name, param[1]);
    }
  });
}

export {
  fromSpec,
  empty,
  extractSchemaName,
  isVisiting,
  startVisiting,
  stopVisiting,
  getSchema,
  resolveRef,
  getSchemaNames,
  hasSchema,
  addSchema,
  merge,
}
/* No side effect */
