// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_JSON from "@rescript/runtime/lib/es6/Stdlib_JSON.js";
import * as Stdlib_JsExn from "@rescript/runtime/lib/es6/Stdlib_JsExn.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";
import * as OpenapiParser from "@readme/openapi-parser";

function jsonToSpec(json) {
  let obj = Stdlib_JSON.Decode.object(json);
  if (obj === undefined) {
    return {
      TAG: "Error",
      _0: "Invalid OpenAPI spec: root is not an object"
    };
  }
  let pathsDict = Stdlib_Option.getOr(Stdlib_Option.flatMap(obj["paths"], Stdlib_JSON.Decode.object), {});
  let infoObj = Stdlib_Option.getOr(Stdlib_Option.flatMap(obj["info"], Stdlib_JSON.Decode.object), {});
  let openAPISpec_openapi = Stdlib_Option.getOr(Stdlib_Option.flatMap(obj["openapi"], Stdlib_JSON.Decode.string), "3.1.0");
  let openAPISpec_info = {
    title: Stdlib_Option.getOr(Stdlib_Option.flatMap(infoObj["title"], Stdlib_JSON.Decode.string), "Untitled API"),
    version: Stdlib_Option.getOr(Stdlib_Option.flatMap(infoObj["version"], Stdlib_JSON.Decode.string), "0.0.0"),
    description: Stdlib_Option.flatMap(infoObj["description"], Stdlib_JSON.Decode.string)
  };
  let openAPISpec_paths = Object.fromEntries(Object.entries(pathsDict).map(param => [
    param[0],
    param[1]
  ]));
  let openAPISpec_components = Stdlib_Option.map(obj["components"], _comp => ({
    schemas: Stdlib_Option.map(Stdlib_Option.flatMap(Stdlib_Option.flatMap(Stdlib_JSON.Decode.object(_comp), c => c["schemas"]), Stdlib_JSON.Decode.object), schemas => Object.fromEntries(Object.entries(schemas).map(param => [
      param[0],
      param[1]
    ])))
  }));
  let openAPISpec = {
    openapi: openAPISpec_openapi,
    info: openAPISpec_info,
    paths: openAPISpec_paths,
    components: openAPISpec_components
  };
  return {
    TAG: "Ok",
    _0: openAPISpec
  };
}

async function resolve(source, timeout) {
  try {
    let options = {
      timeoutMs: Stdlib_Option.getOr(timeout, 60000)
    };
    return jsonToSpec(await OpenapiParser.bundle(source, options));
  } catch (raw_err) {
    let err = Primitive_exceptions.internalToException(raw_err);
    if (err.RE_EXN_ID !== "JsExn") {
      return {
        TAG: "Error",
        _0: "Unknown error resolving spec"
      };
    }
    let message = Stdlib_Option.getOr(Stdlib_JsExn.message(err._1), "Unknown error resolving spec");
    return {
      TAG: "Error",
      _0: `Failed to resolve spec: ` + message
    };
  }
}

async function parseOnly(source, timeout) {
  try {
    let options = {
      timeoutMs: Stdlib_Option.getOr(timeout, 60000)
    };
    return jsonToSpec(await OpenapiParser.parse(source, options));
  } catch (raw_err) {
    let err = Primitive_exceptions.internalToException(raw_err);
    if (err.RE_EXN_ID !== "JsExn") {
      return {
        TAG: "Error",
        _0: "Unknown error parsing spec"
      };
    }
    let message = Stdlib_Option.getOr(Stdlib_JsExn.message(err._1), "Unknown error parsing spec");
    return {
      TAG: "Error",
      _0: `Failed to parse spec: ` + message
    };
  }
}

async function bundleSpec(source, timeout) {
  try {
    let options = {
      timeoutMs: Stdlib_Option.getOr(timeout, 60000)
    };
    let bundled = await OpenapiParser.bundle(source, options);
    return {
      TAG: "Ok",
      _0: bundled
    };
  } catch (raw_err) {
    let err = Primitive_exceptions.internalToException(raw_err);
    if (err.RE_EXN_ID !== "JsExn") {
      return {
        TAG: "Error",
        _0: "Unknown error bundling spec"
      };
    }
    let message = Stdlib_Option.getOr(Stdlib_JsExn.message(err._1), "Unknown error bundling spec");
    return {
      TAG: "Error",
      _0: `Failed to bundle spec: ` + message
    };
  }
}

async function validateSpec(source, timeout) {
  try {
    let options = {
      timeoutMs: Stdlib_Option.getOr(timeout, 60000)
    };
    return jsonToSpec(await OpenapiParser.validate(source, options));
  } catch (raw_err) {
    let err = Primitive_exceptions.internalToException(raw_err);
    if (err.RE_EXN_ID !== "JsExn") {
      return {
        TAG: "Error",
        _0: "Unknown error validating spec"
      };
    }
    let message = Stdlib_Option.getOr(Stdlib_JsExn.message(err._1), "Unknown error validating spec");
    return {
      TAG: "Error",
      _0: `Failed to validate spec: ` + message
    };
  }
}

export {
  jsonToSpec,
  resolve,
  parseOnly,
  bundleSpec,
  validateSpec,
}
/* Stdlib_JsExn Not a pure module */
