// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CodegenError from "./types/CodegenError.res.mjs";

let Warning_toString = CodegenError.Warning.toString;

let Warning_print = CodegenError.Warning.print;

let Warning = {
  toString: Warning_toString,
  print: Warning_print
};

let CodegenError$1;

export {
  CodegenError$1 as CodegenError,
  Warning,
}
/* No side effect */
